### ISSUE TITLE
Micro g causes yt videos too not load after 40-120 secounds since yesterday

### ISSUE THREAD

**Issue by BlueStarBRS** [microg/GmsCore#1887] opened 2023-03-03 03:21 UTC
![image](https://user-images.githubusercontent.com/25110093/222623240-648f7169-8138-4eb4-952e-31b4964da2a9.png)

**Comment by Vankers** [comment] 2023-03-03 06:13
Me too

**Comment by kazimmt** [comment] 2023-03-03 11:26
Isn't it duplicate of #1870

**Comment by ale5000-git** [comment] 2023-03-03 11:45
Im' not sure but maybe it is related to the missing headers reported in #1835

**Comment by Ran-Mewo** [comment] 2023-03-03 13:04
I am having this issue too
although it doesn't seem like #1870 since the video loads and plays but after some seconds/minutes it stops working
and I don't really know how this is related #1835

**Comment by JwanKaro** [comment] 2023-03-03 21:24
Same, but I've the vanced microg version 0.2.24.220220

![Screenshot_20230303-221730.jpg](https://user-images.githubusercontent.com/62551381/222831895-ecdc6ffc-764a-4b3d-a8d2-bbfb6a963348.jpg)

**Comment by NekiMutanLik** [comment] 2023-03-03 22:37
Same, when i switched to yahoo account it worked perfectly.

**Comment by dyharlan** [comment] 2023-03-04 07:11
This issue also leaked onto normal youtube that's not using microG

**Comment by JwanKaro** [comment] 2023-03-04 08:27
> This issue also leaked onto normal youtube that's not using microG

That's sadly not the case.

![Screenshot_20230304-092612_YouTube.jpg](https://user-images.githubusercontent.com/62551381/222885537-1034309b-18d6-424f-8ce5-7063811a343c.jpg)

**Comment by Preetmungara** [comment] 2023-03-04 09:26
It's coming on my normal account in original application also.

**Comment by JwanKaro** [comment] 2023-03-04 14:05
Well, this is gonna take a while to get fixed, I wrote myself a little script, that extracts all my subscription and resubscribe to them in my working account..

**Comment by Ran-Mewo** [comment] 2023-03-04 17:24
> Well, this is gonna take a while to get fixed, I wrote myself a little script, that extracts all my subscription and resubscribe to them in my working account..

Could I have such a script?

**Comment by JwanKaro** [comment] 2023-03-04 19:03
> > Well, this is gonna take a while to get fixed, I wrote myself a little script, that extracts all my subscription and resubscribe to them in my working account..
> 
> Could I have such a script? 

Sure buddy, but this only works on browser with console. 
Because you have to manually copy the url of channels you subscribed to, there is a small snippet, that does exactly that.

It's not a pretty code nor perfect. It's just cobbled together code with simple instructions.

**Comment by JwanKaro** [comment] 2023-03-05 11:00
Here is the “script” with instructions
[gist](https://gist.github.com/JwanKaro/4b9aba3888a6b12a6fb4a2085f2823ca) (https://gist.github.com/JwanKaro/4b9aba3888a6b12a6fb4a2085f2823ca)

**Comment by JwanKaro** [comment] 2023-03-07 21:45
A #potential #fix that worked for me, is by setting a YouTube user id or handle.

[https://www.theverge.com/23403217/youtube-handle-url-how-to](How to set a YouTube handle)

Or it could be, that I'm in a new location.

**Comment by luximus-hunter** [comment] 2023-03-08 08:50
Mine miraculously works again. It could be because I live in the Netherlands, or cuz I:

1. Deleted MicroG and ReVanced
2. Logged in to my Google account on my browser.
3. Deleted MicroG from my devices (with a bit of looking around).
4. Reinstalled MicroG and ReVanced.
5. Logged in again

It didn't work right away but like a few hours later. I hope this helps!

**Comment by jimmylad** [comment] 2023-03-09 06:28
> It's coming on my normal account in original application also.

I found that the problem happened in my original app only if I had Vanced running in the background. If I completely quit Vanced then the original app worked without issue.

**Comment by jimmylad** [comment] 2023-03-10 18:30
I didn't use MicroG and Vanced for a week and I came back to it this week and magically everything is working OK again. I'm in France on a UK account. I haven't reinstalled or changed anything.

**Comment by JwanKaro** [comment] 2023-03-10 20:40
Well, it's a wifi problem. 
When I use my Mobile Data it works, but on a wifi connection it doesn't.

**Comment by KibSquib48** [comment] 2023-03-10 21:13
could it be related to the quality settings? by default it loads lower quality on mobile data

**Comment by JwanKaro** [comment] 2023-03-10 21:22
> could it be related to the quality settings? by default it loads lower quality on mobile data

That is sadly not the case; on mobile and wifi the quality ist 720p. I've a 100 Mb/s on wifi and 2 Mb/s on mobile.

**Comment by jimmylad** [comment] 2023-03-10 21:27
Works fine for me on both Wifi and mobile

**Comment by hegi2k** [comment] 2023-03-10 21:34
Does it maybe have something todo with the microg version? I have vanced micro G which was installed before from using vanced. I update it to the last version with the vanced manager.

**Comment by JwanKaro** [comment] 2023-03-10 23:08
> Does it maybe have something todo with the microg version? I have vanced micro G which was installed before from using vanced. I update it to the last version with the vanced manager. I guess there is a non vanced microg version but i did not find a offial APK for it.

You can find it on there GitHub page, even if you installed it. YouTube revanced won't work with the official one. 

[https://github.com/microg/GmsCore](MicroG)

**Comment by jonas-resch** [comment] 2023-05-31 17:23
For me it seems to work again with the newest official YouTube app version 18.20.34 (downloaded via the Aurora Store) on the following devices:
- Samsung Galaxy Tab S5e Wifi with microG LineageOS build (LOS: 20-20230411-microG-gts4lvwifi, microG 0.2.27.223616)
- Google Pixel 3 with microG LineageOS build (LOS: 19-20230314-microG-blueline, microG: 0.2.27.223616)

**Comment by Goscomat** [comment] 2023-06-01 17:54
After Jonas' reply I was excited to try it out. The first video did play, so I assumed it was fixed. But now it gets stuck at 40 seconds again. I'm on e OS with the same version of MicroG.

**Comment by jonas-resch** [comment] 2023-06-01 18:27
@Goscomat idk what spell I cast yesterday, today it doesn't work anymore... Sorry for giving you hope 😅

**Comment by ILoveOpenSourceApplications** [comment] 2024-06-24 04:53
If you're a ReVanced/RVX user, there's already a fix available for this. Please patch again and read the instructions. If you're a stock YouTube user, well stay here for a fix I guess.

**Comment by BlueStarBRS** [comment] 2024-07-04 21:33
> Well, it's a wifi problem. 
> When I use my Mobile Data it works, but on a wifi connection it doesn't.
> 

What bs you're talkin 😂

**Comment by BlueStarBRS** [comment] 2024-07-04 21:35
Im closing the issue only bs im reading here the original problem is fixed ans Mirco g got replaced with a new one.

**Closed** 2024-07-04 21:35 UTC
Labels: bug

**Comment by jonas-resch** [comment] 2024-07-05 07:50
It hasn't been fixed for the original microg. There's only a workaround which involves using ReVanced and the [ReVanced fork of microg](https://github.com/ReVanced/GmsCore).

I think that this issue should be fixed in the original microg too. Since this issue affects the original microg in combination with the stock, unpatched YouTube app.
