### ISSUE TITLE
Microg Not Login with Google Play Games

### ISSUE THREAD

**Issue by SocialFly** [microg/GmsCore#1650] opened 2022-01-29 03:52 UTC
Microg installed and everything is fine , the settings stuffs also. But when login games required google play games integration. Installed GPG but Account Details not Included in GPG . Games login with play games really Stucks All the way down.is there Solution for  this or Any Alternates.

**Comment by ale5000-git** [comment] 2022-01-29 18:01
Duplicate of #163

microG has never supported Google Play Games, I'm not saying that it will never happen but it needs a lot of time as most of things.

**Closed by ale5000-git** 2022-01-29 18:01 UTC
Labels: bug
