### ISSUE TITLE
About Play Integrity API

### ISSUE THREAD

**Issue by j0110** [microg/GmsCore#1771] opened 2022-08-31 10:26 UTC
Hi,
It would be great to add the possibility to check for Play Integrity API directly with MicroG (as it is already done with Safety Net), to get rid of the real Play Store and just relying on MicroG structure !
Thanks a lot

**Comment by paolo-caroni** [comment] 2023-05-08 09:11
There is much MIT licensed app that do this, the problem is that microg seems to not support play integrity API yet.

**Comment by paolo-caroni** [comment] 2023-05-16 14:01
> @j0110 It is handled directly in microG but it is the library compiled in the app itself that check also for Play Store but FakeStore can spoof it almost perfectly.
> 
> There were some code changes in FakeStore that have already been merged that will improve the situation. But there isn't a new version released yet.

Sorry but no, the release of FakeStore 0.2.0 don't solve this issue, Play Integrity API dosn't run, also Play Integrity is not listed as supported on the [wiki](https://github.com/microg/GmsCore/wiki/Implementation-Status).

**Comment by ale5000-git** [comment] 2023-05-17 18:39
[Play Integrity API Checker](https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck) report success on my phone.

It is possible the problem is not microG.
I'm not completely sure but I think Play Integrity API is just SafeNet with some additional checks and maybe a different interface but the base checks are the same.

**Comment by paolo-caroni** [comment] 2023-05-17 19:52
Interesting, you have fakstore or google play as market?
![Uploading Screenshot_20230517-215043_Play Integrity API Checker.png…]()

**Comment by paolo-caroni** [comment] 2023-05-17 19:56
![Screenshot_20230517-215043_Play Integrity API Checker](https://github.com/microg/GmsCore/assets/2750264/90d304a9-32a1-4742-b2a9-7263cb5d0568)

**Comment by j0110** [comment] 2023-05-21 08:49
> [Play Integrity API Checker](https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck) report success on my phone.
> 
> It is possible that the problem is not microG. I'm not completely sure but I think Play Integrity API is just SafeNet with some additional checks and maybe a different interface but the base checks are the same.

I'm really interested !
How did you succeeded ?

**Comment by Uldiniad** [comment] 2023-05-26 16:40
One function that needs implementing https://developer.android.com/google/play/integrity/reference/com/google/android/play/core/integrity/IntegrityManager.html#requestIntegrityToken(com.google.android.play.core.integrity.IntegrityTokenRequest)

**Comment by paolo-caroni** [comment] 2023-07-15 12:34
Just to clarify, it seems to be a fakestore [issue](https://github.com/microg/FakeStore/issues/36). So probably this issue should be closed. Also @ale5000-git please confirm that you don't use fakestore and this is the reason of your check success.

**Comment by ale5000-git** [comment] 2023-08-10 10:41
Sorry for the late reply.
Yes, with microG GmsCore + Google Play Store you can get this:
![Screenshot](https://github.com/microg/GmsCore/assets/15793015/a8000acd-4c4d-4f64-8572-9f9d32e0a22d)

**Comment by ale5000-git** [comment] 2023-08-10 10:47
Since this issue is only within FakeStore, I'm closing this ticket in favor of this: https://github.com/microg/FakeStore/issues/36

**Closed by ale5000-git** 2023-08-10 10:47 UTC
Labels: question

**Comment by huwenkai26** [comment] 2024-02-15 07:54
> 这么晚才回复很抱歉。 是的，通过 microG GmsCore + Google Play 商店，您可以获得： ![截屏](https://private-user-images.githubusercontent.com/15793015/259714327-a8000acd-4c4d-4f64-8572-9f9d32e0a22d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5ODM5MDAsIm5iZiI6MTcwNzk4MzYwMCwicGF0aCI6Ii8xNTc5MzAxNS8yNTk3MTQzMjctYTgwMDBhY2QtNGM0ZC00ZjY0LTg1NzItOWY5ZDMyZTBhMjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA3NTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMWQ1ODRhNDEzZjg3NDVhOTQwMWJhZTc0YWEyYzkzODBhOTYzOWY1ZjI5NDBmMGI2NWYzNzE4NWEzOTJiMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M43ZMPsJm8rujvHbxnBmNpzY4rLRPgM4JjJXX8FhbdM)

@ale5000-git How do you install the official play store +microG GmsCore

**Comment by Weissnix4711** [comment] 2024-06-25 15:11
> Sorry for the late reply. Yes, with microG GmsCore + Google Play Store you can get this: ![Screenshot](https://private-user-images.githubusercontent.com/15793015/259714327-a8000acd-4c4d-4f64-8572-9f9d32e0a22d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMjg0MjYsIm5iZiI6MTcxOTMyODEyNiwicGF0aCI6Ii8xNTc5MzAxNS8yNTk3MTQzMjctYTgwMDBhY2QtNGM0ZC00ZjY0LTg1NzItOWY5ZDMyZTBhMjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE1MDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NDNkMjQ3YTNmMjQ5M2ZhNGVhODE5YzIwZDliZjc4MjJhYjdiM2UzZmUyMTJiN2ZkN2I5NWU1YmJhMDM5NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u3_C1tdGLwJ4w1VOqp8K6XlVkIhiiWs2q_gw2Pztrw8)

Hi, sorry for bumping this, but can I just ask what version of the play store you have installed?

I tried on a clean install of LOS 20, with magisk + microg installer revived + play store 41.5.29-29, and while the play store and microg are installed fine, no apps recognise the play store as being installed. I suspect maybe it's an incompatibility between microg and the specific version of the play store I am using, but I'm unsure.
