### ISSUE TITLE
Splitwise can't connect to Google Play Services

### ISSUE THREAD

**Issue by dolohow** [microg/GmsCore#410] opened 2017-08-11 10:37 UTC
I can't login through Google account using `Splitwise application`.  When opening app it says, can't connect to google play services and when you want to log in through Google account, same story.

```
08-11 12:17:03.106   694 23683 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.auth.api.signin.service.START pkg=com.google.android.gms } U=0: not found
08-11 12:17:03.107   694   706 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@c9891fd
08-11 12:17:03.107 11150 11220 E GmsClient: unable to connect to service: com.google.android.gms.auth.api.signin.service.START on com.google.android.gms
```

**Comment by SebLz** [comment] 2017-12-27 18:41
I can confirm I have the same issue (mi5 - microg for lineage os - microg 0.2.4-107-g0596d2c)

**Comment by ale5000-git** [comment] 2022-05-10 13:26
Duplicate of #497

**Closed by ale5000-git** 2022-05-10 13:26 UTC
Labels: duplicate
