### ISSUE TITLE
[com.google.android.apps.maps] Latest Google Maps no longer works

### ISSUE THREAD

**Issue by dimaryaz** [microg/GmsCore#1736] opened 2022-06-06 20:40 UTC
**Affected app**
Name: Maps
Package id: com.google.android.apps.maps

**Describe the bug**
Google Maps versions 1066536935 and 1066546582 no longer seem to work. First symptom was, I couldn't open the details of any business and couldn't get directions (though it _did_ work a couple times after I restarted the app). I tried clearing the storage - and now, Google Maps just freezes when I try to open it.

**To Reproduce**
1. Install latest Google Maps
2. Search for anything
3. Open details or get directions
4. The results never finish loading

**Expected behavior**
(Everything should work as before.)

**Screenshots**

**System**
Android Version: 11
Custom ROM: Lineage for MicroG 18.1

**microG**
microG Core version: 0.2.24.214816
microG Self-Check results: All ticked

**Additional context**
Here's output from `adb logcat` (I tried to remove some of the garbage). Unfortunately, I don't know if these are new errors because I don't even know the version code for the last working Google Maps, so can't try it.

Class loader issues?

```
D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
W droid.apps.map: ClassLoaderContext classpath size mismatch. expected=1, found=0 (PCL[/system/framework/org.lineageos.platform.jar*1006563850] | PCL[])
D nativeloader: classloader namespace configured for unbundled product apk. library_path=/product/priv-app/GmsCore/lib/arm64:/product/priv-app/GmsCore/GmsCore.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64
W GmsDynamiteLoaderImpl: No such module known: com.google.android.gms.providerinstaller.dynamite
D GmsDynamiteLoaderImpl: unimplemented Method: getModuleVersion for com.google.android.gms.providerinstaller.dynamite
D GmsDynamiteLoaderImpl: createModuleContext for com.google.android.gms.cronet_dynamite at version 2
W droid.apps.map: Unsupported class loader
W droid.apps.map: Skipping duplicate class check due to unsupported classloader
W droid.apps.map: Unsupported class loader
E system_server: Invalid class loader spec: =UnsupportedClassLoaderContext=
E PackageDexUsage: Unsupported context?
D GmsProviderInstaller: Initializing provider for com.google.android.apps.maps
I cr_CronetLibraryLoader: Cronet version: 91.0.4472.120, arch: aarch64
E ActivityThread: Failed to find provider info for com.google.android.googlequicksearchbox.GsaPublicContentProvider
E ActivityThread: Failed to find provider info for com.google.android.googlequicksearchbox.GsaPublicContentProvider
V NativeCrypto: Registering com/google/android/gms/org/conscrypt/NativeCrypto's 288 native methods...
W ActivityManager: Unable to start service Intent { act=grpc.io.action.BIND cmp=com.google.android.googlequicksearchbox/com.google.android.libraries.assistant.auto.tng.gmm.grpc.startup.GmmEndpointService } U=0: not found
W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@829d345
D GmsProviderInstaller: Installed default security provider GmsCore_OpenSSL
```

`requestGoogleAccountsAccess` not implemented?

```
D GmsProviderInstaller: Installed default security provider GmsCore_OpenSSL
D GmsDummySvc: onBind: Intent { act=com.google.android.mobstore.service.START pkg=com.google.android.gms }
D GmsAuthProvider: Call from com.google.android.apps.maps
E FontsProvider: query: content://com.google.android.gms.fonts [_id, file_id, font_ttc_index, font_variation_settings, font_weight, font_italic, result_code] query = ? [Google Sans Text]
D FontsProvider: openFile: content://com.google.android.gms.fonts/file/1337 mode: r
E FontsProvider: query: content://com.google.android.gms.fonts [_id, file_id, font_ttc_index, font_variation_settings, font_weight, font_italic, result_code] query = ? [Google Sans Text:500]
D ChimeraServiceProvider: serviceIntentCall: com.google.android.gms.mdisync.service.START -> Intent { act=com.google.android.gms.mdisync.service.START pkg=com.google.android.gms cmp=com.google.android.gms/org.microg.gms.DummyService }
D FontsProvider: openFile: content://com.google.android.gms.fonts/file/1337 mode: r
D GmsDummySvc: onBind: Intent { act=com.google.android.gms.mdisync.service.START pkg=com.google.android.gms cmp=com.google.android.gms/org.microg.gms.DummyService }
D GmsAuthProvider: Call from com.google.android.apps.maps
D GmsAuthProvider: Call from com.google.android.apps.maps
D GmsLocReportingSvc: onBind: Intent { act=com.google.android.gms.location.reporting.service.START pkg=com.google.android.gms }
W GmsAuthManagerSvc: Not implemented: requestGoogleAccountsAccess(com.google.android.apps.maps)
D ClearcutLoggerService: bound by: GetServiceRequest{serviceId=CLEARCUT_LOGGER, gmsVersion=222208000, packageName='com.google.android.apps.maps', extras=Bundle[{}]}
D GmsAuthManagerSvc: getToken: account:XXXXXX scope:^^_account_id_^^ extras:Bundle[{androidPackageName=com.google.android.apps.maps, clientPackageName=com.google.android.apps.maps, service_connection_start_time_millis=92857091}], notify: false
D GmsAuthManagerSvc: getToken: account:XXXXXX scope:^^_account_id_^^ extras:Bundle[{androidPackageName=com.google.android.apps.maps, clientPackageName=com.google.android.apps.maps, service_connection_start_time_millis=92857094}], notify: false
D GmsAuthManagerSvc: getToken: account:XXXXXX scope:^^_account_id_^^ extras:Bundle[{androidPackageName=com.google.android.apps.maps, clientPackageName=com.google.android.apps.maps, service_connection_start_time_millis=92857103}], notify: false
D GmsAuthManagerSvc: getToken: AuthResponse{auth=XXXXXX, accountId=XXXXXX}
D GmsAuthManagerSvc: getToken: AuthResponse{auth=XXXXXX, accountId=XXXXXX}
D GmsAuthManagerSvc: getToken: account:XXXXXX scope:^^_account_id_^^ extras:Bundle[{androidPackageName=com.google.android.apps.maps, clientPackageName=com.google.android.apps.maps, service_connection_start_time_millis=92857093}], notify: false
D GmsAuthManagerSvc: getToken: AuthResponse{auth=XXXXXX, accountId=XXXXXX}
D GmsDummySvc: bound by: GetServiceRequest{serviceId=LANGUAGE_PROFILE, gmsVersion=222208000, packageName='com.google.android.apps.maps', extras=Bundle[{}]}
```

"Unknown field id 12" - though I'm guessing it's nothing.

```
D SafeParcel: Unknown field id 12 in com.google.android.gms.clearcut.LogEventParcelable, skipping.
D GmsDummySvc: bound by: GetServiceRequest{serviceId=LIGHTWEIGHT_NETWORK_QUALITY, gmsVersion=222208000, packageName='com.google.android.apps.maps', extras=Bundle[{}]}
D SafeParcel: Unknown field id 12 in com.google.android.gms.clearcut.LogEventParcelable, skipping.
D SafeParcel: Unknown field id 12 in com.google.android.gms.clearcut.LogEventParcelable, skipping.
V SMSHelper: Unsupported attachment type: application/smil
D SafeParcel: Unknown field id 12 in com.google.android.gms.clearcut.LogEventParcelable, skipping.
D GmsAuthProvider: Call from com.google.android.apps.maps
D SafeParcel: Unknown field id 12 in com.google.android.gms.clearcut.LogEventParcelable, skipping.
I chatty  : uid=10095(com.google.android.gms) Binder:4083_4 identical 3 lines
D SafeParcel: Unknown field id 12 in com.google.android.gms.clearcut.LogEventParcelable, skipping.
D GmsPhenotypeSvc: bound by: GetServiceRequest{serviceId=PHENOTYPE, gmsVersion=222208000, packageName='com.google.android.apps.maps', extras=Bundle[{}]}
D GmsPhenotypeSvc: register2(com.google.android.apps.maps, 1066546582, [Ljava.lang.String;@a5be2c8, [I@6e8af61, null)
```

**Comment by dimaryaz** [comment] 2022-06-07 02:32
Found the last working version: 1066514671 (11.30.4).

Though when I run it, the same three errors show up in logcat, so I guess none of them are relevant?

**Comment by dimaryaz** [comment] 2022-06-07 16:47
Just tried installing it - but no, didn't make a difference.

**Comment by freechelmi** [comment] 2022-08-10 08:29
Confirmed on eOS 1.2 0.2.24.214816-18

**Comment by ale5000-git** [comment] 2022-10-05 08:52
Testo di origine
Latest Google Maps works for me with the latest [nightly build](https://microg.org/dl/core-nightly.apk) of microG GmsCore and no longer nag about Play Services update, if not the case for you please write here.

**Comment by ale5000-git** [comment] 2022-11-15 13:43
I'm closing it since it is probably fixed and the user disappeared.
If there are still issues please tell me.

**Closed by ale5000-git** 2022-11-15 13:43 UTC
