### ISSUE TITLE
Unable to connect to Google account regulated by Okta

### ISSUE THREAD

**Issue by Tyler-2** [microg/GmsCore#1838] opened 2022-11-29 17:50 UTC
**Describe the bug**
LineageOS 19-20221022-microG-payton, with microG 0.2.24.214816.

My employer uses Google with Okta for authentication. Attempting to add my Google account to my work profile from the Passwords and Accounts settings app successfully redirects me to my Okta after providing my email address. My Okta login goes as expected - I enter my username and password and then provide my TOTP code. But after that, the screen changes a few times and I get two messages that tend to disappear quickly:

"Sorry.... There was a problem communicating with Google servers. Try again later."
and
"Sorry... Your device is contacting Google to save information to your account. This can take a couple of minutes."

In the end the account shows up as added under accounts, and Gmail under that account shows "last synced" whenever it was I tried to add it, but with an error. "Sync is currently experiencing problems. It will be back shortly." The gmail app just dies when I try to launch it. Manual attempts to trigger sync never complete. Calendar gets added when I open Calendar, and it shows "Synced" but items never come through, and the "last synced" time doesn't get updated.

This is similar to https://github.com/microg/GmsCore/issues/472 except in their case they don't seem to get any errors.

**To Reproduce**
Try to add an Okta-managed Google account to your phone, either through the MicroG app or through the Passwords and Accounts section of settings.

**Expected behavior**
Google account is added to phone with no errors, syncs are successful, and Gmail/Calendar apps work.

**Screenshots**
![signal-2022-11-29-124150_004](https://user-images.githubusercontent.com/8560053/204603664-d7cdca32-bd6c-4caf-b997-0096db970b18.png)
![signal-2022-11-29-124150_003](https://user-images.githubusercontent.com/8560053/204603738-bb345ff1-53de-4de6-864a-19eaa7cf0682.png)
![signal-2022-11-29-124150_002](https://user-images.githubusercontent.com/8560053/204603791-e392a583-1cf7-4eed-aa95-a5ecee8ca0ec.png)
![signal-2022-11-29-124741](https://user-images.githubusercontent.com/8560053/204604881-e32449f1-2203-40c9-82f2-2dd577dafcc1.jpeg)

**System**
Android Version: 12
Custom ROM: LineageOS 19 with microG

**Additional context**

**Comment by ale5000-git** [comment] 2022-11-29 19:51
Could you please update microG GmsCore to the latest [nightly build](https://microg.org/dl/core-nightly.apk) and retry?

**Comment by mar-v-in** [comment] 2022-12-01 13:05
The problem is probably unrelated to Okta, but is caused by your workspace admin enforcing device management rules. microG currently does not implement any device management, nor does it make an effort to spoof such an implementation. If device management is not available, apps that use OAuth2 to get access to your Google Workspace account won't work.

**Comment by Sense101** [comment] 2023-02-08 10:27
This seems to be an issue with *any* google account managed by an organisation - you can add it with microg, but nothing actually works with such accounts.

**Comment by ale5000-git** [comment] 2023-03-03 11:48
@Sense101: Have you tried to add the account in the main profile?
I think currently many things do not work in the work profile with microG.

**Comment by danzek** [comment] 2023-09-06 00:35
Any fix for this yet? I keep having sync issues and Gmail, Calendar, Drive, etc. never finish syncing and show nothing. I keep seeing in Accounts "Sync is currently experiencing problems. It will be back shortly."

**Comment by fynngodau** [comment] 2024-11-18 13:39
Likely this is resolved with v0.3.4, as it supports workspace accounts with basic integrity that mandate a lockscreen.

**Comment by ale5000-git** [comment] 2024-11-18 14:00
I'm closing it, if someone has still problems with the latest version please write here.

**Closed by ale5000-git** 2024-11-18 14:00 UTC
Labels: bug
