### ISSUE TITLE
OneDrive Crash

### ISSUE THREAD

**Issue by waddt123** [microg/GmsCore#1298] opened 2020-12-02 17:51 UTC
**Describe the bug**
OneDrive Crash

**To Reproduce**
1…MicroG Version：0.2.12
2…OneDrive is OK
3…Update 0.2.13/0.2.14
4…OneDrive Crash
Log：

java.lang.IllegalStateException: A fatal developer error has occurred. Class name: zzf. Start service action: com.google.firebase.auth.api.gms.service.START. Service Descriptor: com.google.firebase.auth.api.internal.IFirebaseAuthService. 
	at com.google.android.gms.common.internal.BaseGmsClient$a.zza(SourceFile:13)
	at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(SourceFile:6)
	at com.google.android.gms.common.internal.BaseGmsClient$b.handleMessage(SourceFile:35)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at com.google.android.gms.internal.common.zze.dispatchMessage(SourceFile:1)
	at android.os.Looper.loop(Looper.java:173)
	at android.os.HandlerThread.run(HandlerThread.java:65)

**System**
Android Version: Android8
Custom ROM: MIUI10

**Comment by mar-v-in** [comment] 2020-12-06 10:23
Duplicate of #1254

**Closed by mar-v-in** 2020-12-06 10:23 UTC
Labels: duplicate
