### ISSUE TITLE
F-Droid repo does not update/contain up-to-date versions?

### ISSUE THREAD

**Issue by rugk** [microg/GmsCore#1545] opened 2021-08-28 12:06 UTC
**Describe the bug**
In #1544 I discovered that for some reason my LineageOS4microG did have an outdated microG version ([v0.2.19.211515](https://github.com/microg/GmsCore/releases/tag/v0.2.19.211515) installed – I did report this strange behavior in https://github.com/lineageos4microg/docker-lineage-cicd/issues/217 BTW.
As such I wanted to update and the verison to [v0.2.22.212658](https://github.com/microg/GmsCore/releases/tag/v0.2.22.212658).
However, I could refresh the F-Droid repo as much as I want, it did not download and install the update.

In the end I ended up manually downloading and installing the APK…

**To Reproduce**
1. Have v0.2.19.211515 installed.
2. Use the F-Droid and refresh there.

**Expected behavior**
Download and install latest update.

**Screenshots**
N/A

**System**
Android Version: 11
Custom ROM: LineageOS 18.1

**Additional context**
The repo is enabled. It is `https://microg.org/fdroid/repo?fingerprint=9BD06727E62796C0130EB6DAB39B73157451582CBD138E86C468ACC395D14165`.

PS: On https://microg.org/fdroid/repo it still shows "2017" in the footer.

**Comment by chris42** [comment] 2021-08-28 12:20
I think this is a fdroid bug. If you remove the repository and readd it, normally the update then shows.

**Comment by rugk** [comment] 2021-08-28 15:58
Oh yeah, I remember that I searched for `microG Core` and also did not found the app and wondered how/where I can find it. (all other apps like Unified…/location stuff were shown though)

Opened https://gitlab.com/fdroid/fdroidclient/-/issues/2260

**Comment by ale5000-git** [comment] 2021-08-29 11:29
UnifiedNlp (no GAPPS) in the main F-Droid repo has the same internal name of microG so microG may be listed under UnifiedNlp (no GAPPS).
There is nothing that could be easily done other than disable the main F-Droid repo or search it manually under UnifiedNlp (no GAPPS).

**Comment by rugk** [comment] 2021-08-29 14:57
Ah that is the issue…

> There is nothing that could be easily done other than disable the main F-Droid repo or search it manually under UnifiedNlp (no GAPPS).

But wait… why? It works when you re-add the microG repo, so it is not the case that "nothing could be done". As such, the issue seems to only occur when first the F-Droid repo and then the microG one is indexed?

**Comment by ale5000-git** [comment] 2021-08-29 19:48
Both "UnifiedNlp (no GAPPS)" and "microG" are listed in a merged element, the external name is one of both (I don't know what criterion it use to choose).

**Comment by ale5000-git** [comment] 2023-09-02 12:33
"UnifiedNlp (no GAPPS)" was removed from F-Droid so the problem is fixed.

**Closed by ale5000-git** 2023-09-02 12:33 UTC
Labels: bug
