### ISSUE TITLE
N26 actions tab loads forever

### ISSUE THREAD

**Issue by deviant** [microg/GmsCore#1207] opened 2020-10-03 02:06 UTC
In N26, the actions tab shows a [placeholder screen](https://i.imgur.com/vQvZWpr.png) forever. If no GMS implementation is installed, this does not happen. I spent a decent amount of time tracking this down to the wallet API — I believe that its existence makes N26 think there is support (or makes it attempt to test for support), but since the IOwService does nothing, it just waits for a response forever. After some more searching, I also came across [this Reddit thread](https://old.reddit.com/r/number26bank/comments/huacw1), which arrives at the same conclusion.

I believe that #971, #372, and #626 are caused by this as well, and there's probably more apps out here with the same behaviour that haven't been reported yet (indeed, the N26 bug had a Reddit post but no relevant issue here), so this would probably be good to fix sooner rather than later. I spent quite some time looking through decompiler output and the GMS docs to see if I could figure out the exact sequence of events that would happen with Google's implementation (and thus the minimum necessary API implementation), but I'm not familiar enough with the GMS internals (or Android, for that matter) to do so.

Here's the logcat for posterity:

```
09-30 19:26:45.732 10287 10287 W umber26.androi: Accessing hidden method Landroid/view/View;->setTransitionVisibility(I)V (dark greylist, linking)
09-30 19:26:45.815 21282 21282 D GmsWalletPaySvc: onBind: Intent { act=com.google.android.gms.wallet.service.BIND pkg=com.google.android.gms }
09-30 19:26:45.820 21282  2770 D SafeParcel: Unknown field id 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
09-30 19:26:45.820 21282  2770 D SafeParcel: Unknown field id 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
09-30 19:26:45.820 21282  2770 D SafeParcel: Unknown field id 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
09-30 19:26:45.821 21282  2770 D GmsWalletPaySvc: bound by: GetServiceRequest{serviceId=WALLET, gmsVersion=12451000, packageName='de.number26.android', extras=Bundle[{}]}
09-30 19:26:45.822 21282 28197 D GmsWalletOwSvc: onTransact [unknown]: 14, android.os.Parcel@60e40e7, 17
09-30 19:26:45.842 21282 21282 D GmsMeasureBrokerSvc: onBind: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
09-30 19:26:45.851 21282 28197 D SafeParcel: Unknown field id 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
09-30 19:26:45.851 21282 28197 D SafeParcel: Unknown field id 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
09-30 19:26:45.851 21282 28197 D SafeParcel: Unknown field id 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
09-30 19:26:45.851 21282 28197 D GmsMeasureBrokerSvc: bound by: GetServiceRequest{serviceId=MEASUREMENT, gmsVersion=12451000, packageName='de.number26.android', extras=Bundle[{}]}
09-30 19:26:45.870 21282 28197 D SafeParcel: Unknown field id 2 in com.google.android.gms.measurement.internal.EventParcel, skipping.
09-30 19:26:45.871 21282 28197 D SafeParcel: Unknown field id 3 in com.google.android.gms.measurement.internal.EventParcel, skipping.
09-30 19:26:45.871 21282 28197 D SafeParcel: Unknown field id 4 in com.google.android.gms.measurement.internal.EventParcel, skipping.
09-30 19:26:45.871 21282 28197 D SafeParcel: Unknown field id 5 in com.google.android.gms.measurement.internal.EventParcel, skipping.
09-30 19:26:45.871 21282 28197 D SafeParcel: Unknown field id 3 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.871 21282 28197 D SafeParcel: Unknown field id 5 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.871 21282 28197 D SafeParcel: Unknown field id 6 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.871 21282 28197 D SafeParcel: Unknown field id 7 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.871 21282 28197 D SafeParcel: Unknown field id 9 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.871 21282 28197 D SafeParcel: Unknown field id 10 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.871 21282 28197 D SafeParcel: Unknown field id 12 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.871 21282 28197 D SafeParcel: Unknown field id 13 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.871 21282 28197 D SafeParcel: Unknown field id 14 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.871 21282 28197 D SafeParcel: Unknown field id 15 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.871 21282 28197 D SafeParcel: Unknown field id 16 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.871 21282 28197 D SafeParcel: Unknown field id 17 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.872 21282 28197 D SafeParcel: Unknown field id 18 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.872 21282 28197 D SafeParcel: Unknown field id 22 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.872 21282 28197 D GmsMeasureSvcImpl: f1: de.number26.android
09-30 19:26:45.872 21282 28197 D SafeParcel: Unknown field id 2 in com.google.android.gms.measurement.internal.EventParcel, skipping.
09-30 19:26:45.872 21282 28197 D SafeParcel: Unknown field id 3 in com.google.android.gms.measurement.internal.EventParcel, skipping.
09-30 19:26:45.872 21282 28197 D SafeParcel: Unknown field id 4 in com.google.android.gms.measurement.internal.EventParcel, skipping.
09-30 19:26:45.872 21282 28197 D SafeParcel: Unknown field id 5 in com.google.android.gms.measurement.internal.EventParcel, skipping.
09-30 19:26:45.872 21282 28197 D SafeParcel: Unknown field id 3 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.872 21282 28197 D SafeParcel: Unknown field id 5 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.872 21282 28197 D SafeParcel: Unknown field id 6 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.872 21282 28197 D SafeParcel: Unknown field id 7 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.872 21282 28197 D SafeParcel: Unknown field id 9 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.872 21282 28197 D SafeParcel: Unknown field id 10 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.872 21282 28197 D SafeParcel: Unknown field id 12 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.872 21282 28197 D SafeParcel: Unknown field id 13 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.873 21282 28197 D SafeParcel: Unknown field id 14 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.873 21282 28197 D SafeParcel: Unknown field id 15 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.873 21282 28197 D SafeParcel: Unknown field id 16 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.873 21282 28197 D SafeParcel: Unknown field id 17 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.873 21282 28197 D SafeParcel: Unknown field id 18 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.873 21282 28197 D SafeParcel: Unknown field id 22 in com.google.android.gms.measurement.internal.AppMetadata, skipping.
09-30 19:26:45.873 21282 28197 D GmsMeasureSvcImpl: f1: de.number26.android
09-30 19:26:45.873 21282 28197 D GmsMeasureSvcImpl: f10: ActionsFragment
```

The relevant lines are of course the following:

```
09-30 19:26:45.815 21282 21282 D GmsWalletPaySvc: onBind: Intent { act=com.google.android.gms.wallet.service.BIND pkg=com.google.android.gms }
09-30 19:26:45.821 21282  2770 D GmsWalletPaySvc: bound by: GetServiceRequest{serviceId=WALLET, gmsVersion=12451000, packageName='de.number26.android', extras=Bundle[{}]}
09-30 19:26:45.822 21282 28197 D GmsWalletOwSvc: onTransact [unknown]: 14, android.os.Parcel@60e40e7, 17
```

**Comment by fdawans** [comment] 2020-10-14 12:04
Hello, I have the same issue, and I can't make a transfer anymore on version 3.51.2 (202040000).
I didn't manage to downgrade using Titanium Backup.
How did you go back to the previous version? Apkmirror?

**Comment by deviant** [comment] 2020-10-14 12:05
@fdawans where did I say anything about downgrading?

**Comment by fdawans** [comment] 2020-10-14 12:08
So you kept that version?
I checked the reddit thread, I will follow the instructions there.

**Comment by deviant** [comment] 2020-10-14 12:10
@fdawans I uninstalled microG and switched to GApps

**Comment by laurentS** [comment] 2020-10-16 11:42
Hi, I have the same issue. Tested with N26 version 3.51.2 and 3.52.202041002. I can't do development in java, but happy to help with testing, investigating and moral support :)

**Comment by brumela** [comment] 2020-11-24 08:42
I can confirm this, n26 version 3.45 is last version that is working.

**Comment by ArchangeGabriel** [comment] 2020-11-26 11:44
N26 3.53 works for me.

**Comment by ArchangeGabriel** [comment] 2020-11-26 15:36
(Just to be clear: in this version, they removed “Actions” and replaced it with “Card”, which just works)

**Comment by ale5000-git** [comment] 2022-05-18 07:31
I'm closing it since it is no longer an issue.

**Closed by ale5000-git** 2022-05-18 07:31 UTC
