### ISSUE TITLE
safetynet failed

### ISSUE THREAD

**Issue by bemyfrnd** [microg/GmsCore#1427] opened 2021-03-28 11:55 UTC
I am using lineage os 17.1 whyred microg build. Android 10
Device is xiaomi redmi note 5 pro. Not using gapps obviously.
I tried magisk hide, safetynet universal bypass module, props module for fingerprint, droidguard.
Every option in microg is ticked.
In microg , registration and safetynet turns off automatically.
In magisk , safetynet test says api error. And in root checker appp, it says fail (can't access google play services).
Help would be really appreciated!

**Comment by andrew-ld** [comment] 2021-03-28 13:32
sorry but currently microg is not able to give a valid safety net answer

https://github.com/microg/RemoteDroidGuard/issues/24

**Comment by bemyfrnd** [comment] 2021-03-28 14:10
> sorry but currently microg is not able to give a valid safetynet answer
> 
> [microg/RemoteDroidGuard#24](https://github.com/microg/RemoteDroidGuard/issues/24)

Thanks for the reply! So its unfixed since almost 2 years... I guess it won't be fixed any time soon....
Is there any other trick or workaround or something?

**Comment by andrew-ld** [comment] 2021-03-28 14:43
no

**Comment by 0purple** [comment] 2021-04-11 10:04
@bemyfrnd https://github.com/microg/GmsCore/issues/1435#issuecomment-817279916

**Comment by Axolord** [comment] 2021-04-16 14:38
Please close this issue, it is a duplicate of the mentioned Issue 24 on RemoteDroidGuard.
SafetyNet will probably never be passable again on microG and soon not even on any Android with an unlocked bootloader, due to new hardware. More info in the mentioned issue.

**Closed** 2021-04-21 13:12 UTC
Labels: bug
