### ISSUE TITLE
Add hide launcher button

### ISSUE THREAD

**Issue by DrJackMehoff** [microg/GmsCore#2266] opened 2024-03-28 04:49 UTC
Thank you for the time toy spent on the project. I was wondering if you could create a hide from phone launcher button like the previous microg. I don't use the app and use the phone from stock so being able to hide it from the app drawer permanently would be appreciated like the older version of microg. Thanks!

**Comment by marcdw1289** [comment] 2024-03-28 05:22
Duplicate of #2263.

**Comment by DrJackMehoff** [comment] 2024-03-28 05:37
> Duplicate of #2263.

I apologize for the duplicate. Thank you for the heads. Please disregard this.

**Closed** 2024-03-28 05:37 UTC
Labels: enhancement
