### ISSUE TITLE
Crashes with some apps requiring location

### ISSUE THREAD

**Issue by Unb0rn** [microg/GmsCore#840] opened 2019-06-16 10:16 UTC
Hello! I am seeing problems with some location-requiring apps crashing (specifically, Yandex Maps, Yandex Eda, Gett Taxi), while others (Yandex Transport, Yanex Taxi) can get the location successfully. All these apps are running in a work-profile created with Shelter app. All apps are able to register successfully with GCM and receive pushes.
[logcat.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3294021/logcat.txt)

**Comment by oldosfan** [comment] 2019-06-19 00:50
You should use the Mapbox build

**Comment by Unb9rn** [comment] 2019-06-20 06:55
> You should use the Mapbox build

Mapbox version changed nothing... Still crashes

**Comment by ildar** [comment] 2019-06-20 09:07
Yandex apps don't use GMap so mapbox/etc. is unrelated.
JFYI I have Yandex Taxi and another app using Yandex maps running fine

**Comment by Unb9rn** [comment] 2019-06-20 09:43
> Yandex apps don't use GMap so mapbox/etc. is unrelated. JFYI I have Yandex Taxi and another app using Yandex maps running fine

Yep, it works, and even detects location correctly, until I press the triangle button to refresh location,- that's when it crashes. (Only Yandex Maps, Yandex Taxi and Yandex Transport does not have this problem)

**Comment by mar-v-in** [comment] 2019-06-20 10:08
@Unb0rn are you using any sandboxing or work profile app?

**Comment by Unb9rn** [comment] 2019-06-20 11:15
> @Unb0rn are you using any sandboxing or work profile app?

As I've already told, I am using Shelter for setting up work profile. Nevertheless, I've also tried running those apps without isolation. Result is the same...

**Comment by mar-v-in** [comment] 2019-06-20 11:34
OK, I wasn't able to reproduce this issue in Shelter either, but I do have some pending changes in my local build that might be related, so maybe I accidentally fixed it already.

**Comment by klemens** [comment] 2019-06-20 11:49
I have the same problem (same exception as in the log from @Unb0rn: `java.lang.SecurityException: UID … is not related to packageName […]`) with several apps, but only since I applied the framework-patch to allow non-system apps to provide (location) services.

As the exception message points to `getAndCheckPackage`, maybe the recent 4713797edc21e3f3b2a26194056f63b307e67ef6 fixes the issue? Unfortunately I haven't had time yet to build my own version that includes this commit.

**Comment by Vavun** [comment] 2019-06-21 14:29
@mar-v-in 

> but I do have some pending changes in my local build

Can you sync your latest commits with github repo please ?

**Comment by klemens** [comment] 2019-06-24 14:48
I have now built and installed latest master (including 4713797edc21e3f3b2a26194056f63b307e67ef6) and this has fixed the problem (`java.lang.SecurityException: UID … is not related to packageName`) for me.

I had to reinstall the affected apps (otherwise I would get `java.lang.SecurityException: Not allowed to bind to service Intent`) but now they work fine again.

**Comment by ale5000-git** [comment] 2022-05-18 07:00
It should be fixed with the latest microG GmsCore, if not please open another ticket.

**Closed by ale5000-git** 2022-05-18 07:00 UTC
