### ISSUE TITLE
Android Pay support?

### ISSUE THREAD

**Issue by youcanaddthenameofyourorganizationlater** [microg/GmsCore#437] opened 2017-11-06 11:12 UTC
Is there Android Pay support?
My payment app just shows "Sorry, something went wrong."

I would really like to see this..

**Comment by ShapeShifter499** [comment] 2017-11-06 12:37
This is a duplicate of a issue in opened. Can you comment on that one to show support?  I already added money to BountySource for that issue.   https://github.com/microg/android_packages_apps_GmsCore/issues/361

**Comment by ShapeShifter499** [comment] 2017-11-06 12:39
#361 duplicate. I hope this can be added one day.

**Comment by rugk** [comment] 2017-12-10 08:38
This issue can be closed, as it is a duplicate.

**Comment by ale5000-git** [comment] 2022-05-10 14:14
As laready said, duplicate of #361

**Closed by ale5000-git** 2022-05-10 14:14 UTC
Labels: duplicate
