### ISSUE TITLE
Test SafetyNet attestation fails: CTS profile does not match

### ISSUE THREAD

**Issue by cmonty14** [microg/GmsCore#1798] opened 2022-10-02 12:49 UTC
**Describe the bug**
Running test SafetyNet attestation fails with this error:
_Warning: CTS profile does not match_

**To Reproduce**
1. Open 'microG Settings'
2. Click on 'Google SafetyNet'
3. Activate 'Allow device attestation'
4. Click on 'Test SafetyNet attestation'

**Expected behavior**
Running 'Test SafetyNet attestation' completes w/o error.

**System**
Android Version: 12
Custom ROM: 19-20220823-microG-dumpling
microG Services Core version: 0.2.24.214816

**Screenshots**
![Screenshot_20221002-144213_microG Services Core](https://user-images.githubusercontent.com/12523591/193454832-2e380606-891a-45a9-9fd1-5276509a9e52.png)

**Comment by defkev** [comment] 2022-10-03 08:54
CTS profile mismatch usually boils down to the fingerprint reported by your phone being unknown to Google:

> Custom ROM: 19-20220823-microG-dumpling

so find a fingerprint matching your device Google has certified and use that in a custom profile:

```xml
 <data key="Build.FINGERPRINT" value="..." />
```

I never bothered to look into this with microG as all my apps insisting on device attestation work as long as i hide the unlocked bootloader and root.

Cheers

**Comment by mjnck** [comment] 2022-10-10 07:08
You can use this to fake cts profile https://github.com/luk1337/ih8sn

**Comment by defkev** [comment] 2022-10-10 08:02
I tried MagiskHide Props Config (https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf) over the weekend:

1. Flash zip
2. Reboot
3. Run `props` in elevated terminal and spoof fingerprint
4. Reboot
5. Done

![Screenshot_20221010-095140_microG_Services_Core](https://user-images.githubusercontent.com/5265345/194821288-699efaf8-6330-4992-853f-d60178ee14c7.png)

**Comment by cmonty14** [comment] 2022-10-14 14:53
Thanks for sharing this instruction.

Could you please advise what should be entered here?
![Screenshot_20221014-164745_Terminalemulator](https://user-images.githubusercontent.com/12523591/195876948-4049ebe9-3790-4413-84f0-ed31d26165a7.png)

**Comment by defkev** [comment] 2022-10-15 01:33
`f` then pick your device (e.g. `OnePlus 5T`) then your API (e.g. `31` for Android 12), save and reboot.

If there is no fingerprint matching your API just pick the latest available, imho the API isn't too important but the vendor is so you don't get offered grab for download incompatible with your device.

https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/README.md#can-i-use-any-fingerprint

**Comment by mar-v-in** [comment] 2022-10-30 23:42
There are several reasons for SafetyNet to not pass. Passing SafetyNet is an issue independent of microG and whatever is required to pass SafetyNet with original Google services on your device / OS applies for microG as well. Support for specific devices or OS are out of scope here.

**Closed by mar-v-in** 2022-10-30 23:42 UTC
Labels: bug

**Comment by Forage** [comment] 2024-02-05 20:16
If you are using Magisk, remove the Universal SafetyNet Fix module and reset plus remove the MagiskHide Props Config module and use [PlayIntegrityFix](https://github.com/chiteroman/PlayIntegrityFix) instead. Worked for my OnePlus 6.

**Comment by defkev** [comment] 2024-02-20 10:10
I can confirm that PlayIntegrityFix does indeed work in-place of Universal SafetyNet Fix w/ MagiskHide Props Config:

![Screenshot_20240220-110526_microG_Services](https://github.com/microg/GmsCore/assets/5265345/f6b7096c-7a40-4824-9100-711154216d4c)

This has the added benefit that its all in a single package, especially since neither Universal SafetyNet Fix nor MagiskHide Props Config seem to be maintained any more.

**Comment by weskerty** [comment] 2024-10-23 07:34
> I can confirm that PlayIntegrityFix does indeed work 

No for my
