### ISSUE TITLE
Revolut top up credit does not work

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [microg/GmsCore#626] opened 2018-10-01 11:39 UTC
*** Bug ***
Top up credit in the bank account of the Revolut App does not work. After clicking the + symbol the app seems to load "something" but gets stuck.

Revolut works with original gapps.

MicroG version: 0.2.5.12879
Revolut version: 5.17

**Comment by Nanolx** [comment] 2018-10-02 18:08
It is recommended, that you first try with the latest 0.2.6.13280 release and if it still doesn't work, provide a logcat, otherwise no one can have a look at the issue.

**Comment by cRaZy-bisCuiT** [comment] 2018-10-04 05:59
I will do so after this update got pushed to LineageOS for MicroG - mido build. Thanks!

**Comment by cedricpim** [comment] 2018-10-05 16:44
Same issue here:

MicroG version: 0.2.6.13280
Revolut: 5.18

From logcat, I get this whenever I click the topup button:

```
10-05 18:42:12.291 16262 16262 D GmsWalletPaySvc: onBind: Intent { act=com.google.android.gms.wallet.service.BIND pkg=com.google.android.gms }
10-05 18:42:12.328 16262 19416 D SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
10-05 18:42:12.328 16262 19416 D GmsWalletPaySvc: bound by: GetServiceRequest{serviceId=WALLET, gmsVersion=11910000, packageName='com.revolut.revolut', extras=Bundle[{}]}
10-05 18:42:12.330 16262 19416 D GmsWalletOwSvc: onTransact [unknown]: 14, android.os.Parcel@5c048e0, 17
```

It can be consistently reproduced.

**Comment by cRaZy-bisCuiT** [comment] 2018-10-12 07:34
I forgot to upload the logcat, but yes, it's the same.

**Comment by maciekmm** [comment] 2018-10-14 16:41
I've been spamming the top-up button a few times, tried to force close the application and eventually it opened. Now it works every time. Set up auto top-up to not worry about this in the future ;)

**Comment by bocekm** [comment] 2018-11-15 09:21
The same here, trying it multiple times does not help.
Revolut 5.24, MicroG 0.2.6.13280.

**Comment by cRaZy-bisCuiT** [comment] 2018-11-19 08:59
You can also add your Revolut IBAN to PayPal and transfer money from there. It was ~ 1 day to arrive at Revolut.

In addition, if you transfer money online but have insufficient funds, you'll be redirected to a top up credit screen in Revolut and then you can charge your account instantly.

**Comment by matttbe** [comment] 2018-11-28 21:29
I just disabled MicroG, a downgrade was done at the same time. Then when updating to the latest version of MicroG in the background, I tried to top-up and it worked!

**Comment by cRaZy-bisCuiT** [comment] 2018-12-06 13:42
So while MicroG was disabled the Top Up worked for you? Did you restart your phone after updating?

**Comment by cedricpim** [comment] 2018-12-29 23:16
@cRaZy-bisCuiT how do you stop and deactivate micro-g?

**Comment by bocekm** [comment] 2019-01-01 22:14
Thanks, @matttbe. Disabling MicroG is really a workaround.
@cedricpim, at least on Lineage 15.1: Android settings -> Apps & notifications -> See all apps -> Show system -> find microG Services Core -> Disable.

**Comment by cRaZy-bisCuiT** [comment] 2019-01-09 14:55
With version 5.29 it does just work for me. Can anyone confirm this? No idea if a more recent version breaks that.

**Comment by ferlanero** [comment] 2019-02-26 18:18
For me, Revolut Top Up (5.12 version) is not working with MicroG 0.2.6.13280. Is there something I have to check? Thank you.

**Comment by bocekm** [comment] 2019-02-27 13:18
@ferlanero, first update to the latest Revolut (5.35), just to be sure. For me, it works. But the fact that it works for me may still be a result of the procedure [I described above](https://github.com/microg/android_packages_apps_GmsCore/issues/626#issuecomment-450760844).

**Comment by okias** [comment] 2019-04-26 08:31
I can confirm issue with recent LineageOS microG and latest Revolut :(

**Comment by cRaZy-bisCuiT** [comment] 2019-05-07 08:30
The problem persits. Any ideas?

**Comment by codethief** [comment] 2019-09-15 23:33
I just upgraded Revolut to v6.6.1 and the "Add money" not only looks a bit different now but also seems to work!

**Comment by cRaZy-bisCuiT** [comment] 2019-11-12 09:33
For me it works now. Can the issue be closed?

**Comment by ferlanero** [comment] 2020-11-01 09:20
Revolut stop working for me since 7.22 (702200707) version on 27 october 2020 and microG 0.2.13.20.3915 version. The Revolut app just closes after enter personal code.

Someone here has this issue too?

**Comment by matttbe** [comment] 2020-11-03 10:29
@ferlanero I just checked and Revolut version 7.23.3 is working well for me. Same version of microG.
Note that version 7.23.2 was not working but apparently, that was the case on many other phones without microG too. Maybe try to update Revolut to the latest version?

**Comment by matttbe** [comment] 2020-11-03 10:32
(Note that I guess we can close this ticket, apparently we can top up credit for a while now. Here @ferlanero got a different issue. I don't know who can close this ticket)

**Closed** 2022-05-10 12:42 UTC
