### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by reyis4402** [microg/GmsCore#1505] opened 2021-06-30 23:27 UTC
Microg stops working in the background when entering the application with the last update.

**Comment by reyis4402** [comment] 2021-06-30 23:30
https://send.vis.ee/download/7d797d903f1c5ad8/#fLQyz2uxQyoiTABDnuiCDA

**Comment by reyis4402** [comment] 2021-06-30 23:40
I have started again but if I go into the practice, the Microg stops working in the background

**Comment by reyis4402** [comment] 2021-07-01 00:02
![Screenshot_20210701-023545](https://user-images.githubusercontent.com/60405617/124045661-21533380-d9de-11eb-85f3-9e1a93c79088.png)

**Comment by Sapiosenses** [comment] 2021-07-01 03:30
@reyis4402 

When you create a bug report, please use the template provided after using the "open" button, for "Generic bug report", and fill in the details.

As I demonstrated to you in the Telegram microG group, this is not happening on my Android 10 device. Are you using Android 10? How did you install? Please fill in the fields requested in the "generic bug" template.

Thanks.

**Comment by reyis4402** [comment] 2021-07-01 07:54
I'm using Android 11 and installed with Microg Nanodroid.

**Comment by mar-v-in** [comment] 2021-07-01 09:02
Can you please check if commit a431fea (build uploaded to https://microg.org/dl/core-nightly.apk) fixes your issues?

**Comment by reyis4402** [comment] 2021-07-01 09:26
![Screenshot_20210701-122605](https://user-images.githubusercontent.com/60405617/124100929-8dc64500-da67-11eb-85a1-7e91ec08b3b1.png)
![Screenshot_20210701-122608](https://user-images.githubusercontent.com/60405617/124100937-8f900880-da67-11eb-855a-b301dca9cc20.png)

**Comment by reyis4402** [comment] 2021-07-01 09:59
![Screenshot_20210701-125830](https://user-images.githubusercontent.com/60405617/124105656-70768400-da31-11eb-801f-edcff1c8be8e.png)

**Comment by reyis4402** [comment] 2021-07-01 09:59
07-01 12:58:26.217 I/ActivityManager(1583): Killing 13739:com.google.android.gms:ui/u0a240 (adj 905): remove task

**Comment by mar-v-in** [comment] 2021-07-01 10:03
Killing the :ui process when removing the task (that is swiping it away in recent app lists) is intended. The klling of the :persistent process is more relevant here. Unfortunately the logs in your screenshot are cut off and filtered, making it hard to find discover and relevant details.

**Comment by reyis4402** [comment] 2021-07-01 10:09
[logs-2021-07-01-13-07-56.zip](https://github.com/microg/GmsCore/files/6747362/logs-2021-07-01-13-07-56.zip)

**Comment by reyis4402** [comment] 2021-07-01 10:41
Will it be update to fix the problem? @mar-v-in

**Comment by mar-v-in** [comment] 2021-07-01 11:10
Unfortunately still no valuable insights from your log as you filered the output. Can you send me the full log without filter (feel free to send it by mail to bugs at microg.org if you don't want to share it in public).
Have you tried downloading and installing from https://microg.org/dl/core-nightly.apk? Make sure the update is actually installed (shows version "0.2.20.212158-3 (d8e50cb)" in about screen) as some users reported that updating doesn't work as usual (workaround is described here: https://github.com/microg/GmsCore/issues/1503#issuecomment-872097477)

**Comment by reyis4402** [comment] 2021-07-01 11:25
07-01 14:20:53.604 I/ActivityManager(1583): Killing 28083:com.google.android.gms:ui/u0a240 (adj 905): remove task
07-01 14:20:53.604 I/ActivityManager(1583): Killing 28128:com.google.android.gms/u0a240 (adj 700): remove task
07-01 14:20:53.606 I/ActivityManager(1583): Killing 28107:com.google.android.gms:persistent/u0a240 (adj 500): remove task
07-01 14:20:53.683 W/ActivityManager(1583): Scheduling restart of crashed service com.google.android.gms/org.microg.gms.gcm.McsService in 2478520ms for start-requested
07-01 14:20:53.724 W/InputDispatcher(1583): Attempted to unregister already unregistered input channel 'a413ffa com.google.android.gms/org.microg.gms.ui.SettingsActivity (server)'
07-01 14:20:53.724 I/WindowManager(1583): WIN DEATH: Window{a413ffa u0 com.google.android.gms/org.microg.gms.ui.SettingsActivity}

**Comment by reyis4402** [comment] 2021-07-01 11:25
![Screenshot_20210701-142437](https://user-images.githubusercontent.com/60405617/124116870-770af880-da3d-11eb-8722-e8c569290ffe.png)

**Comment by reyis4402** [comment] 2021-07-01 11:27
![IMG_20210701_142738_207](https://user-images.githubusercontent.com/60405617/124117218-d963f900-da3d-11eb-8ca2-c4c6cf76da98.jpg)

**Comment by reyis4402** [comment] 2021-07-01 11:42
@mar-v-in I have installed the test app. But the problem persists. I hope the report helps.

**Comment by reyis4402** [comment] 2021-07-01 11:48
Tutanota- Android 11- ArrowOS
![Screenshot_20210701-144712](https://user-images.githubusercontent.com/60405617/124119517-4c3f9500-da7b-11eb-8e21-ff7a162fd19c.png)

**Comment by reyis4402** [comment] 2021-07-01 11:50
Tutanota does not die in the background like Microg.

**Comment by reyis4402** [comment] 2021-07-01 12:01
https://tutanota.com/blog/posts/open-source-email-fdroid/

**Comment by reyis4402** [comment] 2021-07-01 12:24
But the latest test version works smoother. Within 1 minute, MicroG starts working in the background again.

**Comment by HanabishiRecca** [comment] 2021-07-01 12:55
Can confirm the bug. It starts as intended after boot. But if you openand swipe out the UI, MCS service struggle to restart itself.

![screen](https://user-images.githubusercontent.com/13597663/124126877-8cf7d800-da94-11eb-9613-39e56f8fed31.png)

Android 11 / LOS 18.1

I see a such error: 
```
D GmsGcmMcsSvc: Connection is not enabled or dead.
E ActivityManager: Sending non-protected broadcast org.microg.gms.snet.SERVICE_INFO_RESPONSE from system 3085:com.google.android.gms/u0a164 pkg com.google.android.gms
E ActivityManager: java.lang.Throwable
E ActivityManager:       at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:15910)
E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:16585)
E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:15927)
E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:16741)
E ActivityManager:       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2283)
E ActivityManager:       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2875)
E ActivityManager:       at android.os.Binder.execTransactInternal(Binder.java:1154)
E ActivityManager:       at android.os.Binder.execTransact(Binder.java:1123)

```

**Comment by mar-v-in** [comment] 2021-07-01 14:04
The process being stopped on swiping away is expected behavior, for as long as it restarts within short time. (Android does this to free unneeded resources that were allocated for the UI). This is the same for Tutanota and always was like this in microG (although indeed 0.2.20 had some related changes, but those are already reverted in the nightly apk).

The log @HanabishiRecca submitted also is not a crash or fatal, it's more like a warning.

Please double-check again that you updated to the `0.2.20.212158-3 (d8e50cb)` (https://microg.org/dl/core-nightly.apk). On `0.2.20.212158` such bugs might happen if microG is installed to /system. In that case, updating the normal way is likely to fail and you need to do the workaround described here: https://github.com/microg/GmsCore/issues/1503#issuecomment-872097477

**Comment by HanabishiRecca** [comment] 2021-07-01 14:12
> The process being stopped on swiping away is expected behavior, for as long as it restarts within short time.

I know. But the problem is it can't start again. Also manual process kill and restart doesn't help. The only effective method is reboot.

> Please double-check again that you updated to the `0.2.20.212158-3 (d8e50cb)`

I'm not. I will try it.

**Comment by HanabishiRecca** [comment] 2021-07-01 14:19
Well, seems like it fixed in `0.2.20.212158-3`, thanks 🙂

**Comment by reyis4402** [comment] 2021-07-01 14:54
To continue working in the background, contact Google when the device restarts and changes the connection.

**Comment by mar-v-in** [comment] 2021-07-01 18:55
Closing based on feedback that service automatically restarts within 1 minute.

**Closed by mar-v-in** 2021-07-01 18:55 UTC
Labels: bug
