### ISSUE TITLE
A malicious app can grab valuable private information from logcat dumped by microg

### ISSUE THREAD

**Issue by dilbech** [microg/GmsCore#1316] opened 2020-12-16 08:57 UTC
**Describe the bug**
Logcat contains may be private information (PII) https://en.wikipedia.org/wiki/Personal_data

```
12-16 09:43:40.216  1748  2329 D GmsServicesProvider: query caller=com.google.android.apps.photos name=android_id value=xxxxxxxxxxxxx
12-16 09:43:40.228  1748  2329 D GmsServicesProvider: query caller=com.google.android.apps.photos name=device_country value=<country code redacted>
12-16 09:43:40.259  1748  2329 D GmsAuthManagerSvc: getToken: account:noreply@gmail.com scope:^^_account_id_^^ extras:Bundle[{androidPackageName=com.google.android.apps.photos, clientPackageName=com.google.android.apps.photos, service_connection_start_time_millis=178283}], notify: false
12-16 09:43:40.264  1748  2329 D GmsAuthManagerSvc: getToken: AuthResponse{auth='xxxxxxxxxxxxx', accountId='xxxxxxxxxxxxxx'}
12-16 09:43:40.281  1748  2329 D GmsAuthManagerSvc: getToken: account:noreply@gmail.com scope:oauth2:https://www.googleapis.com/auth/notifications extras:Bundle[{androidPackageName=com.google.android.apps.photos, clientPackageName=com.google.android.apps.photos, service_connection_start_time_millis=178321}], notify: false
12-16 09:43:40.283  1748  2329 D GmsAuthManager: peekAuthToken: com.google.android.apps.photos:xxxxxxxxxxxxxxxxx:oauth2:https://www.googleapis.com/auth/notifications
12-16 09:43:40.285  1748  2329 D GmsAuthManagerSvc: getToken: AuthResponse{auth='ya29.xxxxxxxxx', issueAdvice='stored'}

```

**To Reproduce**
1. install microg or equiv rom
2. open terminal 
3. adb logcat
4. or a malicious app may grab info from logcat

**Expected behavior**

Logcat does not have email addresses or tokens/keys (something like that is there)

SUGGESTION:
May be a flag (debug) in microg settings that will dump these info. 
Better you can log info without real email addresses/tokens. 

**Screenshots**
see above

**System**
Android Version: oreo
micrg version: 15 Dec installed from https://microg.org/fdroid/repo
Custom ROM:  AOSP 

**Additional context**

Lets say some third party app starts grabbing logcat. 
(Of course, I agree user should not install rubbish third-party apps but as you know users may do it).

**Comment by mar-v-in** [comment] 2020-12-16 22:14
Apps normally can't access the logcat entries of other apps, only their own logs. To get more logs they either need root permission or a special permission (`READ_LOGS`) that can only be granted through adb. So effectively this requires debug access to the device.

Beside that, I totally agree. This is a duplicate of #251 though.

**Closed by mar-v-in** 2020-12-16 22:14 UTC
Labels: bug

**Comment by dilbech** [comment] 2020-12-17 07:30
Apologies that I did not do proper search to find the other bug. (Thanks anyway for the quick response).
