### ISSUE TITLE
Location not reported from flutter_background_geolocation

### ISSUE THREAD

**Issue by ocroquette** [microg/GmsCore#1963] opened 2023-06-20 06:18 UTC
**Describe the bug**
flutter_background_geolocation does not get location updates from microG.

**To Reproduce**
1. Install the demo application: https://github.com/transistorsoft/flutter_background_geolocation#-demo-application
2. Start the tracking
3. Open the tracker WUI (http://tracker.transistorsoft.com/<orga>)
4. No position is available

**Expected behavior**
Using the Google Play Services, the location is retrieved from the device and sent to the server.

**System**
Android Version: 13
Custom ROM: CalyxOS 4.10.0

**Additional context**
The issue is reproduceable in the emulator.
I am not entirely sure it is due to microG. If someone has access to a phone with microG using a different distribution, it would be easy to confirm or infirm.

There is also a bug report in the flutter_background_geolocation project: https://github.com/transistorsoft/flutter_background_geolocation/issues/1052

**Comment by MichelJonasz** [comment] 2023-08-08 11:52
Hello,

I can confirm that it seems to be due to microG.
I have the same problem with an application which is using the "flutter_background_geolocation" plugin.

I use /e/ OS 0.13 (based on android 12).
The version of microG Services Core is 0.2.28.231657-26 (6968294)-noen

Please, can you fix this ?
It's really embarrassing.

Regards,

**Comment by mar-v-in** [comment] 2023-08-30 08:47
Unfortunately, I can't reproduce the issue. The demo application linked above does work fine for me, and I can't test with Minutis Mobile as I don't have credentials.

**Comment by mar-v-in** [comment] 2023-08-30 09:29
I checked the version of Minutis Mobile that I got hands on (3.0.16) and it uses version 3.4.0 of tslocationmanager which matches version 4.10.x or 4.11.x of flutter_background_geolocation. I then tried version 4.10.1 of flutter_background_geolocation and can reproduce that it doesn't work on microG, whereas the latest version (4.12.2, based on tslocationmanager 3.4.4) does work.

So it seems the issue was already fixed in tslocationmanager/flutter_background_geolocation.

I'll investigate with the 4.10.1 version of flutter_background_geolocation now, but maybe you can ask the developer of Minutis Mobile to make sure they have the latest version of flutter_background_geolocation.

**Comment by mar-v-in** [comment] 2023-08-31 16:16
The tslocationmanager library which is the core of flutter_background_geolocation is also used by capacity-background-geolocation. Version 5.0.0 of capacity-background-geolocation is using 3.4.0 of tslocationmanager. The version of tslocationmanager that is known to work with microG is 3.4.4, which is available in capacity-background-geolocation version 5.1.2.

Nonetheless I figured what caused the issues with tslocationmanager 3.4.0 and will provide a patch with the next microG version.

**Closed** 2023-09-01 10:00 UTC
Labels: bug, 📍 Location
