### ISSUE TITLE
Info Windows do not work on maps.

### ISSUE THREAD

**Issue by Antonbeard** [microg/GmsCore#289] opened 2017-01-31 19:04 UTC
When you click on a marker, nothing happens. For example, in program TRAFI https://play.google.com/store/apps/details?id=com.trafi.android.tr shoul appear a window: 
![screenshot_155404-31012017](https://cloud.githubusercontent.com/assets/25462424/22479951/601fe36a-e7f8-11e6-929a-a0c93c8e6a0a.png)

**Comment by Antonbeard** [comment] 2017-04-15 08:16
@mar-v-in , Can you comment on why are some of the code commented out? https://github.com/microg/android_packages_apps_GmsCore/blob/master/play-services-core/src/main/java/org/microg/gms/maps/markup/InfoWindow.java

**Comment by mar-v-in** [comment] 2017-04-15 08:29
This code is legacy code from the time we used the osmdroid library to render maps. It won't work if you try to comment it in again.

**Comment by kfpv** [comment] 2022-06-22 13:25
It's an old issue, however I can confirm that it's still not working, even on the newest versions of both MicroG and Trafi.

**Comment by fynngodau** [comment] 2024-10-01 16:57
Info windows in maps are implemented since 0.2.28 / 0.2.29; I would suggest to close this issue.

**Comment by ale5000-git** [comment] 2024-10-02 06:39
The problem should be already fixed, if someone encounter it again with the latest version, then please open a new ticket.

**Closed by ale5000-git** 2024-10-02 06:39 UTC
Labels: 🗺 Maps
