### ISSUE TITLE
Unable to add account on Huawei device (No gms)

### ISSUE THREAD

**Issue by pkcheng** [microg/GmsCore#1468] opened 2021-05-12 07:29 UTC
1. Click 'Add Google Account'
2. Enter Gmail
3. Enter password
4. Showing "Sorry... There was a problem communicating with Google servers. Try again later"

**Comment by mrazorvin** [comment] 2021-08-15 12:06
I have the similarly problem :(

**Comment by Arkert** [comment] 2021-08-19 10:48
The issue is I think signature spoofing. microg cannot do anything

**Comment by ale5000-git** [comment] 2021-08-19 10:53
The issue on Huawei is likely the ban by Google.

**Comment by pkcheng** [comment] 2021-08-19 12:51
There should be a way to fix it, because vanced microg is modified from microg and able to add account on vanced microg

**Comment by Arkert** [comment] 2021-08-19 13:19
> There should be a way to fix it, because vanced microg is modified from microg and able to add account on vanced microg

Because it's an own application. You don't used vance with other official signed apps. You can only use it with vance's application (youtube vanced and music)

**Comment by benyaminl** [comment] 2021-08-24 16:57
Why not use xposed framework for it?

**Comment by ale5000-git** [comment] 2021-08-29 12:01
Vanced simply fake another device, it is a hacky solution.

**Comment by ale5000-git** [comment] 2022-01-26 13:48
Everything should already be fixed on the latest version (microG can now spoof another device) so I close it for now.
Open a new issue if needed.

**Closed by ale5000-git** 2022-01-26 13:48 UTC
