### ISSUE TITLE
[com.whatsapp] Missed calls, notification of messages or calls delayed

### ISSUE THREAD

**Issue by starbrights** [microg/GmsCore#2452] opened 2024-07-21 17:49 UTC
**Affected app**
Name: WhatsApp
Package id: com.whatsapp

**Describe the bug**
If I get called, phone is not ringing. Messages about missed call or messages in general will be notified somewhat later

**To Reproduce**
Just let's send you a message or give you a call.

**Expected behavior**
Phone should ring when a call is given or messages should be received without delay.

**Screenshots**
n.a.

**System**
Android Version: 14
Custom ROM: LOS 21

**microG**
microG Core version: 0.2.27.223616 / 0.3.2 - installed via FDroid
microG Self-Check results: All ticked

Google registration is on (no Google account given), Cloud messaging on and Whatsapp is registered. A count up of messages can be seen. I observe that counter for messages will be not incrementing by 1 but  by 3. - WHY?
If phone is on during a incoming call/message the phone gives acustic signal as expected (but microG message counter is not count up).

**Additional context**
Regarding battery optimization settings.
In microG all selfchecks are fine. In Whatsapp I have two points:
* allow background usage (is checked)
* stop app activity if not used (unchecked).
I think there is not much more that I can do.

It is not as easy to test notification on other apps, as I can usually not trigger them by myself. I found one app (Kleinanzeigen - similar to craigs list), where another used can send messages. Sending messages to me result in expected acustic notification, without a bigger delay (few seconds).  In this case message counter increments for each incoming message by one as expected.

**Comment by lucasmz-dev** [comment] 2024-07-23 23:35
> microG Core version: 0.2.27.223616

You might wanna try 0.3.2, in F-Droid you can set it to receive "beta" updates for the microG components

**Comment by starbrights** [comment] 2024-07-27 08:47
Updated both, core and companion to 0.3.2 as adviced, but no change of behaviour. A call or message doesn't seem to wake up the device. I am curious: can WA work w and w/o PlayServices? Signal seems to have it's own path....

**Comment by Axolord** [comment] 2024-07-27 10:34
I think whatsapp without microG/play services does not receive any messages in the background, only on app opening.

Can you vheck whether whatsapp is registered for gcm? On my device whatsapp calls and messages do not seem to be delayed. In the advanced settings everything is on automatic/15min, but I also dokt know what that means exactly.

**Comment by starbrights** [comment] 2024-07-27 11:17
Some apps have own alternatives for messaging (as Signal). There are a lot of mauals how to install WA w/o Play Store. So I guess this phones have no PlayServices too. And afaik microG replaces them booth.
Yes WA is registered. Now Wifi ping times is 15min too, no idea why 27min this morning. Depends maybe on usage of phone.

**Comment by starbrights** [comment] 2024-07-28 19:47
One more info: 
Tried Kleinanzeige with GCM and let send me messages. That was running fine. 
That means: It can work, but for some reason it doesn't with WA.

**Comment by RizzoV** [comment] 2024-08-04 14:43
Same here, when the phone is in sleep mode multiple apps (WhatsApp, Signal, ProtonMail, ...) face delayed notification. Sometimes notifications won't show up at all until I manually wake the device. MicroG self-check is all ticked and I manually veryfied that MicroG related apps are not battery optimized.

Also, I have a Pixel device and found that this behaviour started once QPR2 was merged into LOS21. I don't know if this is due to MicroG, QPR2 or a mix of both. Coincidentally, QPR2 has seen the introduction of a new battery optimisation interface in apps settings.

**Comment by lucasmz-dev** [comment] 2024-08-04 15:41
How do you have microG installed? Is it regular LOS as a user app? (Since now you can do that)

**Comment by starbrights** [comment] 2024-08-04 16:01
As of me: I installed it as user-app via FDroid. Does the behaviour changes the other way? What is recommended?

**Comment by lucasmz-dev** [comment] 2024-08-04 16:07
Usually it shouldn't cause issues, but there are some privileged permissions for better dealing with push notifications, but even without them it should be fine.

It may be your Google registration is broken. You may try to clear app data from companion, services and the framework, but that'd break things and require the same for other apps

I'd check the last registered dates in the google device registration menu and cloud messaging. What do they say?

**Comment by starbrights** [comment] 2024-08-04 16:08
> Same here, when the phone is in sleep mode multiple apps (WhatsApp, Signal, ProtonMail, ...) face delayed notification. 

Does your Signal uses GCM? As for me this is not - and this doesn't seem to make problems so far (with delay). So I tried that with WA too (deinstall WA+microG, install WA w/o microG). My impression was it solves the issue for the price of higher battery load.  But I couldn't test that long as I need microG for other than GCM... 
Til now I didn't allow GCM, and registration - but behaviour is like before - delay.  So I don't know when WA uses its PlayServices independend notification. Is availability (by install microG) enough, or does it needs to be registered. In the later case you could play around by disable that quickly in microG. Someone with deeper knowledge is needed here.

**Comment by starbrights** [comment] 2024-08-04 16:14
> It may be your Google registration is broken. You may try to clear app data from companion, services and the framework, but that'd break things and require the same for other apps
> 
> I'd check the last registered dates in the google device registration menu and cloud messaging. What do they say?

As I have checked it some time back it looks normal. It is not completly out of work and shows last messages.

ATM it is my phone is not registered at all (because of my experiment above). There is not much documentation (for users as me), what means which setting. At least other notification (app Kleinanzeigen) was running fine. So not sure this is general issue.

**Comment by starbrights** [comment] 2024-08-04 16:18
For me the setting is (translated from German):
* stop app activity while not using (I guess uncheck this)
* allow background usage (checked).

**Comment by RizzoV** [comment] 2024-08-04 16:21
> Does your Signal uses GCM?

Yes

> I'd check the last registered dates in the google device registration menu and cloud messaging. What do they say?

Device registered 5h ago, cloud messaging connected since 53m ago, everything looks normal to me. 

> Just disable "battery optimization" in app settings and allow run in backround

Great to hear you solved it but that shouldn't be necessary on a normally working system :/ Also, applying this on all involved apps may probably have an impact on battery life. Solving the underlying problem would be the ideal solution.

**Comment by lucasmz-dev** [comment] 2024-08-04 16:25
@starbrights FYI if your registration is off you cannot receive push notifications but you probably know that

**Comment by starbrights** [comment] 2024-08-04 16:28
> @starbrights FYI if your registration is off you cannot receive push notifications but you probably know that

Sure. Again - this is just a current test because I assume that "native" signalling (w/o GCM) might work better. Signal was in my case not regisered and works more reliable. So don't be confused.

**Comment by ale5000-git** [comment] 2024-08-12 19:04
Although most of microG works also when installed as user app, if I'm not wrong to wake-up apps it use a system API: [addToTemporaryAllowList](https://android.googlesource.com/platform/prebuilts/fullsdk/sources/android-31/+/refs/heads/androidx-savedstate-release/android/os/PowerExemptionManager.java#525)
So I think this will never works when microG is just an user app.

**Comment by RizzoV** [comment] 2024-08-12 23:18
If confirmed, imho that would be something users need to be clearly warned about before proceeding with the user app installation on LOS.

This issue is a serious pita when daily driving a phone.

**Comment by ale5000-git** [comment] 2024-08-13 00:48
In every case Google Play Services is always a system app, microG already does miracles as is :-)

**Comment by starbrights** [comment] 2024-08-13 12:54
> Although most of microG works also when installed as user app, if I'm not wrong to wake-up apps it use a system API: [addToTemporaryAllowList](https://android.googlesource.com/platform/prebuilts/fullsdk/sources/android-31/+/refs/heads/androidx-savedstate-release/android/os/PowerExemptionManager.java#525) So I think this will never works when microG is just an user app.

The thing is - I tested microG-revived Magisk module instead of user app. But it ends up that I doesn't get all permissions. (SMS and location in background). 
Looking at the issue list of this module: ... the solution is to install (additional/on top ?!?) it as APK.
https://github.com/nift4/microg_installer_revived
"can't grant background location and SMS permission: [download](https://github.com/nift4/microg_installer_revived/raw/master/system/priv-app/microG/microG.apk) & install APK as update" 
 
Well - do I have than a user app again?

**Comment by ale5000-git** [comment] 2024-08-13 12:57
If the app is installed both as system and user app it is still a system app.

**Comment by ale5000-git** [comment] 2024-08-13 15:43
This is how Android works:
The privileged system apps are in /system/priv-app, but the system partition is read-only so obviously when you update them the update go in the data partition but as long as the original file remain in place it is still a privileged system app.
The internal app name (not the filename) and the signature must match but obviously the version can be different.

I'm not sure if it works to install it in the system partition after it being a simple user app.

**Comment by starbrights** [comment] 2024-08-18 18:51
Maybe I could solve the problem. Seems microG needs to be installed as a system app.
So I did:
* deinstall microG (3 apps that have been installed via FDroid)
* create a backup of WA and its data (NeoBackup)
* deinstalled WA (don't keep data)
* installed microg-revived via Magisk
* reboot 
* try to give all permission (does fail for SMS and background location)
* install microG as user app (to get additional permissions - see above in a previous post)
* give all the missed permission
* install Whatsapp / don't open
* give WA all needed permission 
* start WA (it notices a Custom ROM) and re-register with phone number
* start it (and it will be visible in microG/Cloud messages.

At that time it seems to work fine, but I need to recover the message data. I stopped WA.
In neo-backup I set option to just recover Mediadata. Than I recover Mediadata. To bad, this action seems to be recognised by Whatsapp and a Re-Register is required again. I already afraid of get into trouble but it keeps working.

That sound bit difficult. I tried other ways before - delete whatsapp but keep data and reinstall it again .-  but that doesn't force to register in cloudmessage service). I hope that it will keep on going.

**Comment by RizzoV** [comment] 2024-08-19 10:47
@ale5000-git thank you for clearing this up, very appreciated.

I definitely think that a disclaimer in the wiki and a dedicated entry checking microG's  ability to wake up apps when receiving notifications in the self-checks view would be helpful to make users aware of this limitation and possibly avoid it. 

Discovering about this once that dozens of apps have already registered to GCM and trying to fix the issue on a "dirty" system isn't great.

**Comment by ale5000-git** [comment] 2024-08-19 14:35
If you have root you can run this command:
`find /data/data/*/shared_prefs -name 'com.google.android.gms.*.xml' -delete`

It will delete the gms data from all apps causing them to re-register (other app data are left intact).

**Closed** 2024-08-19 17:07 UTC
