### ISSUE TITLE
Nearby Share

### ISSUE THREAD

**Issue by Rexadev** [microg/GmsCore#1850] opened 2022-12-14 07:57 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
https://en.wikipedia.org/wiki/Nearby_Share

**Comment by TheHighGroundWins** [comment] 2022-12-20 04:23
Duplicate of #1272

**Closed** 2022-12-20 06:15 UTC
Labels: duplicate, enhancement
