### ISSUE TITLE
Cannot add a Google account - GmsCore v0.2.7.17455

### ISSUE THREAD

**Issue by z3ru3l** [microg/GmsCore#829] opened 2019-06-07 18:14 UTC
I have installed the latest version of GmsCore (17455), manually build from source. I'm seeing the following weird behaviour:

With every Google Services DISABLED --> Google account is successfully added.
Log:
```06-07 14:54:01.440 26871 26871 D GmsAuthLoginBrowser: pageFinished: https://accounts.google.com/EmbeddedSetup?source=android&xoauth_display_name=Android%20Device&lang=en&cc=us&langCountry=en_us&hl=en-US&tmpl=new_account
06-07 14:54:01.502 26871 26952 D GmsAuthLoginBrowser: JSBridge: getAndroidId 0
06-07 14:54:01.507 26871 26952 D GmsAuthLoginBrowser: JSBridge: notifyOnTermsOfServiceAccepted
06-07 14:54:02.625 26871 26952 D GmsAuthLoginBrowser: JSBridge: log Loading page: identifier
06-07 14:54:02.630 26871 26952 D GmsAuthLoginBrowser: JSBridge: getAccounts
06-07 14:54:02.637 26871 26952 D GmsAuthLoginBrowser: JSBridge: getAndroidId 0
06-07 14:54:02.742 26871 26952 D GmsAuthLoginBrowser: JSBridge: showView
06-07 14:54:02.749 26871 26871 D GmsAuthLoginBrowser: pageFinished: https://accounts.google.com/EmbeddedSetup/identifier?source=android&xoauth_display_name=Android%20Device&lang=en&cc=us&langCountry=en_us&hl=en-US&tmpl=new_account&flowName=EmbeddedSetupAndroid
06-07 14:54:26.154 26871 26952 D GmsAuthLoginBrowser: JSBridge: getAccounts
06-07 14:54:26.169 26871 26952 D GmsAuthLoginBrowser: JSBridge: getDroidGuardResult: ["*******AEThLlyGdLjBRWXIwwBmFeJPgJhDLLZ7Amq8OX0Z6QO_5ENQWEAhYLCoW4raBoFGGjp9IqbCWBzYKLNS_IKiqSn0XR"]
06-07 14:54:27.171 26871 26952 D GmsAuthLoginBrowser: JSBridge: getAndroidId 0
06-07 14:54:27.799 26871 26952 D GmsAuthLoginBrowser: JSBridge: setAccountIdentifier *****gmail.com
06-07 14:54:28.275 26871 26952 D GmsAuthLoginBrowser: JSBridge: log Loading page: signin/v2/challenge/pwd
06-07 14:54:28.397 26871 26952 D GmsAuthLoginBrowser: JSBridge: showView
06-07 14:54:41.759 26871 26952 D GmsAuthLoginBrowser: JSBridge: getDroidGuardResult: ["AEThLlztrPaFcSWAdmuUFpnVuEG6daIQG919OA1S2MtTi93psVmg9K1GWnoW1WLjn4pBTugaTV9154JHG0pM3w9334ufoDEasV9y"]
06-07 14:54:42.760 26871 26952 D GmsAuthLoginBrowser: JSBridge: getAndroidId 0
06-07 14:54:43.282 26871 26952 D GmsAuthLoginBrowser: JSBridge: log Loading page: signinconsent
06-07 14:54:47.837 26871 26952 D GmsAuthLoginBrowser: JSBridge: getAndroidId 0
06-07 14:54:48.251 26871 26952 D GmsAuthLoginBrowser: JSBridge: getAndroidId 0
06-07 14:54:48.260 26871 26871 D GmsAuthLoginBrowser: pageFinished: https://accounts.google.com/EmbeddedSetup/signinconsent?source=android&xoauth_display_name=Android%20Device&lang=en&cc=us&langCountry=en_us&hl=en-US&tmpl=new_account&flowName=EmbeddedSetupAndroid&TL=APDPHBBzO9Oprcrio4jnUKid2jLoUfMfLOymZF34_gon4lLxysFslbMy_Gn3SmWI&cid=1#close
06-07 14:54:48.264 26871 26991 D GmsHttpFormClient: -- Request --
06-07 14:54:48.264 26871 26991 D GmsHttpFormClient: add_account=1&androidId=0&app=com.google.android.gms&client_sig=38918a453d07199354f8b19af05ec6562ced5788&callerPkg=com.google.android.gms&callerSig=38918a453d07199354f8b19af05ec6562ced5788&device_country=us&get_accountid=1&google_play_services_version=17455000&ACCESS_TOKEN=1&lang=en_US&operatorCountry=us&sdk_version=28&service=ac2dm&Token=oauth2_4%2FYgGs4OBh4JCOSZlqNX0jwIOxG6IAG5Opb0zjI2mt9SiTIRpNkpgrJPXjnNRx4cHoDPf6TXW7Pb0n0q_tU21ejHA
06-07 14:54:49.518 26871 26991 D GmsHttpFormClient: -- Response --
06-07 14:54:49.518 26871 26991 D GmsHttpFormClient: Token=aas_et/AKppINbIli1KDrvVN_GXYSij0vVssnxV3BumJEmOpj92mLEALh4N4pK43xFB4wm9I3er10CjlBrZT-hC_Ia1HkGNVSW8xIfAIAbzVv-J7r5cYmHvWtrDC-VNdCboHzIVGA==
06-07 14:54:49.518 26871 26991 D GmsHttpFormClient: Auth=egcJJ46UVEWvmdmIKcF4zBaFqOf8TiLGnkA_Ly26kUdA8sbqoNKImt1lgM9k0Ef1rvCLJg.
06-07 14:54:49.518 26871 26991 D GmsHttpFormClient: SID=egcJJ-se1WHhVSLGKwoMnrvr3p6EiQnykNUlCsJxza5l81yCSDvYPysOmSLsE5lPX7TISg.
06-07 14:54:49.518 26871 26991 D GmsHttpFormClient: LSID=egcJJ-4q0M1FR1QuVlI-iOaybP0P_7uxIRwotHW4V8zXvkjSVqZJKSqyWsRWG6OBnNj9jA.
06-07 14:54:49.518 26871 26991 D GmsHttpFormClient: services=mail,hist,friendview,talk,android,googleplay,cl,youtube
06-07 14:54:49.518 26871 26991 D GmsHttpFormClient: Email=*******@gmail.com
06-07 14:54:49.518 26871 26991 D GmsHttpFormClient: GooglePlusUpdate=0
06-07 14:54:49.518 26871 26991 D GmsHttpFormClient: firstName=******
06-07 14:54:49.518 26871 26991 D GmsHttpFormClient: lastName=**********
```

With any of the Google Services ENABLED --> Google account fails to be added ("Just a sec..." screen looping forever).
Log:
```
06-07 14:52:37.064 26644 26644 D GmsAuthLoginBrowser: pageFinished: https://accounts.google.com/EmbeddedSetup?source=android&xoauth_display_name=Android%20Device&lang=en&cc=us&langCountry=en_us&hl=en-US&tmpl=new_account
06-07 14:52:37.130 26644 26797 D GmsAuthLoginBrowser: JSBridge: getAndroidId 4531090365622828041
06-07 14:52:37.135 26644 26797 D GmsAuthLoginBrowser: JSBridge: notifyOnTermsOfServiceAccepted
06-07 14:52:38.325 26644 26797 D GmsAuthLoginBrowser: JSBridge: log Loading page: identifier
06-07 14:52:38.330 26644 26797 D GmsAuthLoginBrowser: JSBridge: getAccounts
06-07 14:52:38.337 26644 26797 D GmsAuthLoginBrowser: JSBridge: getAndroidId 4531090365622828041
06-07 14:52:38.458 26644 26797 D GmsAuthLoginBrowser: JSBridge: showView
06-07 14:52:38.467 26644 26644 D GmsAuthLoginBrowser: pageFinished: https://accounts.google.com/EmbeddedSetup/identifier?source=android&xoauth_display_name=Android%20Device&lang=en&cc=us&langCountry=en_us&hl=en-US&tmpl=new_account&flowName=EmbeddedSetupAndroid
06-07 14:52:58.873 26644 26797 D GmsAuthLoginBrowser: JSBridge: getAccounts
06-07 14:52:58.890 26644 26797 D GmsAuthLoginBrowser: JSBridge: getDroidGuardResult: ["******AEThLlzUjsFtqEXV4C0Hx6udTrb2lpmu5pN7hXlb_H0ljnUDtzELjZhZTwwKdnaC4bx5e6492t1uZCn8WqVoTTlg9X"]
06-07 14:52:59.893 26644 26797 D GmsAuthLoginBrowser: JSBridge: getAndroidId 4531090365622828041
06-07 14:53:00.429 26644 26797 D GmsAuthLoginBrowser: JSBridge: setAccountIdentifier ******@gmail.com
06-07 14:53:00.882 26644 26797 D GmsAuthLoginBrowser: JSBridge: log Loading page: signin/v2/challenge/pwd
06-07 14:53:00.998 26644 26797 D GmsAuthLoginBrowser: JSBridge: showView
06-07 14:53:17.727 26644 26797 D GmsAuthLoginBrowser: JSBridge: getDroidGuardResult: ["AEThLlwizGxXlNZmDvrewbckKG5CoKt9DNNMb9oanrwWq7hERy6Ex0ZnKcswTQBid4D6SN5VPAUAC4lmvjLJGz8FRi5F7ZwC633v"]
06-07 14:53:18.728 26644 26797 D GmsAuthLoginBrowser: JSBridge: getAndroidId 4531090365622828041
06-07 14:53:19.308 26644 26797 D GmsAuthLoginBrowser: JSBridge: log Loading page: signinconsent
06-07 14:53:20.708 26644 26797 D GmsAuthLoginBrowser: JSBridge: getAndroidId 4531090365622828041
06-07 14:53:21.050 26644 26797 D GmsAuthLoginBrowser: JSBridge: getAndroidId 4531090365622828041
06-07 14:53:21.058 26644 26644 D GmsAuthLoginBrowser: pageFinished: https://accounts.google.com/EmbeddedSetup/signinconsent?source=android&xoauth_display_name=Android%20Device&lang=en&cc=us&langCountry=en_us&hl=en-US&tmpl=new_account&flowName=EmbeddedSetupAndroid&TL=APDPHBArOv24Nrfi-IRsgcs7XQ--NHnzo1Lt8EznuKRt86abzyqmg22RK-iVXDKC&cid=1#close
06-07 14:53:21.062 26644 26820 D GmsHttpFormClient: -- Request --
06-07 14:53:21.062 26644 26820 D GmsHttpFormClient: add_account=1&androidId=3ee1aaae4824bc09&app=com.google.android.gms&client_sig=38918a453d07199354f8b19af05ec6562ced5788&callerPkg=com.google.android.gms&callerSig=38918a453d07199354f8b19af05ec6562ced5788&device_country=us&get_accountid=1&google_play_services_version=17455000&ACCESS_TOKEN=1&lang=en_US&operatorCountry=us&sdk_version=28&service=ac2dm&Token=oauth2_4%2FYgEVnsoOpT8KjDskHFYKTJTnbcG5e42P8J8l9aJ6OV3pTka6R55V-Nv0_Ztaoq7i9JnfyBGNk3-evoYVMYrnCgA
06-07 14:53:22.025 26644 26820 W GmsAuthLoginBrowser: onException: java.io.IOException: Error=ServerError
06-07 14:53:50.766 26871 26871 D GmsPhenotypeCfgProvider: unimplemented Method: onCreate
```
I'm running a custom AOSP build. The Self-Check passes except for the "UnifiedNlp status", which is expected.

*UDPATE*
Build latest commit Version 0.2.7.17455-65-mapbox (1e49e95)
I can only add a google account WITHOUT the "Google device registration" enabled.

**Comment by ale5000-git** [comment] 2019-06-07 21:12
I think that the problem is here: https://github.com/microg/android_packages_apps_GmsCore/blob/master/play-services-core/src/main/java/org/microg/gms/auth/login/LoginActivity.java#L273
I'm not sure what is exactly.

**Comment by mar-v-in** [comment] 2019-06-20 11:46
With Google device registration disabled, it won't try to associate your android id with your Google Account. This might cause issues with some Google apps like Play Store. You can still enable device registration after account login if you need it for push messages.

**Comment by z3ru3l** [comment] 2019-06-20 15:58
> With Google device registration disabled, it won't try to associate your android id with your Google Account. This might cause issues with some Google apps like Play Store. You can still enable device registration after account login if you need it for push messages.

Is there any way to fix that? Can this be related to phone model (Pixel 3)? My final goal is to set the "Google device registration" on by editing the source code and build it on my personal aosp rom.

**Comment by sharljimhtsin** [comment] 2019-08-17 13:51
the same error " GmsAuthLoginBrowser: onException: java.io.IOException: Error=ServerError" in my adnroid box...

can anyone help?

**Comment by ale5000-git** [comment] 2022-01-26 14:03
Everything should already be fixed on the latest version of microG GmsCore so I close it for now.
Open a new issue if needed.

**Closed by ale5000-git** 2022-01-26 14:03 UTC
Labels: 👥 Google Accounts
