### ISSUE TITLE
MicroG doesn't load functionnality status, Google registration + GCM doesn't work

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [microg/GmsCore#1363] opened 2021-01-12 21:46 UTC
**Describe the bug**

MicroG doesn't connect to google servers, and therefore can't connect to GCM, doesn't register apps. It also looks like it doesn't load the status of Google registering, GCM and Safetynet:

https://i.imgur.com/JWrrfqR.png

The status of the functionnalities doesn't load. After a few minutes, it eventually loads and I can interact with them, but it still doesn't register apps for GCM. It's like the status for the 3 functionnalities is ON visually, but OFF in reality.

**To Reproduce**

I'm on Redmi Note 8T (willow), rooted with Magisk 21.2, custom ROM Xtended XR v4.0 official. Signature spoofing is activated. All checkboxes in Self-check are checked. The ROM is freshly clean installed. Root access is granted to MicroG. I tried installing MicroG from an apk, from Nanodroid zip, and from MinMicroG zip. The problem stays the same.

**Expected behavior**

MicroG should load the status of the functionnalities at start, and Google registering + GCM should work normally.

**Screenshots**
https://i.imgur.com/JWrrfqR.png
https://i.imgur.com/UPRubt5.png
https://i.imgur.com/LYSUQuq.png
https://i.imgur.com/MK1F4Rf.png

**System**
Android Version: 11
Custom ROM: Xtended XR v4.0

**Additional context**

**Comment by chris42** [comment] 2021-01-12 21:53
Have you tried the checkin command as described [here](https://github.com/microg/GmsCore/wiki/Helpful-Information)?
Also check if not by accident the confirm new apps option in the extended cloud messaging settings is activated.

**Comment by LeVraiRoiDHyrule** [comment] 2021-01-12 22:50
> 
> 
> Have you tried the checkin command as described [here](https://github.com/microg/GmsCore/wiki/Helpful-Information)?
> Also check if not by accident the confirm new apps option in the extended cloud messaging settings is activated.

Thanks for your answer. I just tried running the command, the command completed, but it doesn't change the problem. I also tried with the number in dialer app, it's the same.

**Comment by chris42** [comment] 2021-01-12 23:16
Probably then helpful to get a log when you are using the notification tester.

**Comment by LeVraiRoiDHyrule** [comment] 2021-01-12 23:30
> 
> 
> Probably then helpful to get a log when you are using the notification tester.

Ok. How do I get Microg's log ?

**Comment by chris42** [comment] 2021-01-12 23:33
It is the regular system log. Either via an app like Matlog or via `adb logcat`

**Comment by ale5000-git** [comment] 2021-01-12 23:34
I suggest also to update microG to version 0.2.17.204714

**Comment by LeVraiRoiDHyrule** [comment] 2021-01-12 23:35
> 
> 
> I suggest also to update microG to version 0.2.17.204714

I did it just after sending the original post, but apparently it didn't change the problem

**Comment by Lowell13** [comment] 2021-01-13 19:22
Hello there, a previous post was already open for the last version. Seeing yours, I guess it's not fixed yet. As I suggested [here](https://github.com/microg/GmsCore/issues/1329#issue-773023625) I would recommend downgrading to 0.2.15. Register is working on this version, it seems like it's taking an awful amount on time on 0.2.16 and so probably on 0.2.17.

**Comment by didierm** [comment] 2021-01-25 17:16
I can reproducilby trace this down to **MagiskHide**.

### Test environment

* device #1 : Xiaomi Mi 9T (davinci) : official LineageOS 17.1 A10 with **built-in** microG (https://download.lineage.microg.org/davinci/lineage-17.1-20201203-microG-davinci.zip)
* device #2 : Xiaomi Mi Note 10 Lite (toco) : unofficial LineageOS 17.1 A11 (no built-in microG)

* microG GCM Registration tested with the app "Push Notification Tester" : https://github.com/bbindreiter/PushNotificationTester_App (https://play.google.com/store/apps/details?id=com.firstrowria.pushnotificationtester)

* tested with Magisk 21.2 and 21.4

* device#1 : tested with microG being built-in (v0.2.14)
* device#2 : tested with microG being installed as
  * a user app (v0.2.15 and v0.2.17)
  * a systemless Magisk module (v0.2.16 and subsequent user-space update to v0.2.17) : https://github.com/nift4/microg_installer_revived
  * a systemized user app (v0.2.17) : https://github.com/Magisk-Modules-Repo/terminal_systemizer (with module update for A11 : https://forum.xda-developers.com/t/module-terminal-app-systemizer-v17-3-1.3585851/post-84330057)

### Results

* on 'device #1' (built-in microG), push notifications work with or without MagiskHide, as expected.
**Note** : the "**microG Services Core**" app (com.google.android.gms) is *NOT* present in the MagiskHide app list.

* on 'device #2' (no built-in microG), push notifications **ONLY** work when MagiskHide is **disabled**.
**Note** : the "**microG Services Core**" app (com.google.android.gms) is always present in the MagiskHide app list, no matter the installation method (user app, systemless module, systemized app). MagiskHide is automatically enabled for the app, end stays enabled (even after manually disabling).

**Comment by didierm** [comment] 2021-01-25 18:48
Update : 

For the first time since the abovementioned extensive testing, Google registration just suddenly and automatically succeeded (after about two hours idling) out of the blue on device#2, with Magisk 21.4, microG 0.2.17 (systemized app), MagiskHide enabled and "microG Services Core" selected in MagiskHide.

```
D GmsGcmTrigger: Ignoring Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) }: network is offline, scheduling new attempt.
D GmsGcmMcsSvc: Scheduling reconnect in 5 seconds...
D GmsGcmMcsSvc: I/O error: java.net.SocketException: Software caused connection abort
D GmsGcmMcsSvc: Teardown initiated, reason: java.net.SocketException: Software caused connection abort
D GmsGcmMcsSvc: Scheduling reconnect in 10 seconds...

D GmsGcmMcsSvc: Connection is not enabled or dead.
D GmsGcmTrigger: Not connected to GCM but should be, asking the service to start up. Triggered by: Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) }
D GmsGcmMcsSvc: Connect initiated, reason: Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) }
D GmsGcmMcsSvc: Connection is not enabled or dead.
D GmsGcmMcsSvc: Starting MCS connection...
D GmsGcmMcsSvc: Connected to mtalk.google.com:5228
D GmsGcmMcsSvc: Activated SSL with mtalk.google.com:5228
D GmsGcmMcsSvc: Scheduling heartbeat in 1433 seconds...
D GmsGcmMcsSvc: Sending login request...
D GmsGcmMcsOutput: Outgoing message: LoginRequest{id=android-30, domain=mcs.android.com, user=3479331547891678554, resource=3479331547891678554, auth_token=3477756659473058717, device_id=android-3049119bc7e4bd5a, setting=[Setting{name=new_vc, value=1}], adaptive_heartbeat=false, use_rmq2=true, auth_service=ANDROID_ID, network_type=1}
D GmsGcmMcsOutput: Write MCS version code: 41
D GmsGcmMcsInput: Reading from MCS version: 41
D GmsGcmMcsInput: Incoming message: LoginResponse{id=android-30, jid=user@firebase.com/notifications, last_stream_id_received=1, server_timestamp=1611599017655}
D GmsGcmMcsSvc: Logged in
D GmsGcmMcsInput: Incoming message: IqStanza{type=SET, id=, extension=Extension{id=12, data=[size=0]}}
W GmsGcmMcsSvc: Unknown message: IqStanza{type=SET, id=, extension=Extension{id=12, data=[size=0]}}
```

After a reboot, microG Google device registration is disabled again, and push notifications do not arrive.


As the Google registration (and hence receiving push notifications) is totally unpredictable in these circumstances, it is probably advisable to keep MagiskHide disabled for now.

**Comment by lss4** [comment] 2021-01-27 01:12
> Update :
> 
> For the first time since the abovementioned extensive testing, Google registration just suddenly and automatically succeeded (after about two hours idling) out of the blue on device#2, with Magisk 21.4, microG 0.2.17 (systemized app), MagiskHide enabled and "microG Services Core" selected in MagiskHide.
> 
> After a reboot, microG Google device registration is disabled again, and push notifications do not arrive.
> 
> As the Google registration (and hence receiving push notifications) is totally unpredictable in these circumstances, it is probably advisable to keep MagiskHide disabled for now.

Auto-hiding GMS/microG was an intended behavior (see [this](https://github.com/topjohnwu/Magisk/issues/3559)). While you can disable MagiskHide for microG/DroidGuard Helper, it would be re-enabled when you reboot.

While this didn't help with the issues I'm having, if the behavior is indeed causing trouble for microG it's better to relay this question to Magisk with more information.

**Comment by didierm** [comment] 2021-01-27 08:34
@lss4 Thanks for the Magisk issue, which I seem to have missed when searching the netz.

**Comment by didierm** [comment] 2021-01-27 19:27
Note : in my experience, a reboot *is* required to reenable Google Registration after disabling MagiskHide for microG.

As rebooting re-enables MagiskHide for microG, this makes the entire exercise moot ; disabling MagiskHide entirely is required to enable Google registration and related push notifications for the case as documented in https://github.com/microg/GmsCore/issues/1363#issuecomment-766972002 .

**Comment by Master0ne** [comment] 2021-02-19 18:38
~~Issue confirmed with microG Services Core Version `0.2.17.204714` and `0.2.16.204713` on ArrowOS 11 on a POCO X3 NFC, as well as the fix by downgrading to to `0.2.15.204713`.~~

OK, that's awkward, I have just reinstalled microG Services Core Version `0.2.17.204714` and uninstalled microG DroidGuard Helper (because SafetyNet hasn't been working with microG for a long time anyway) and now the issue seems to be gone!

I'm using Magisk Canary (21410) and even reinstalling microG DroidGuard Helper after uninstalling it didn't stop it from working.

In MagiskHide microG Services Core is checked (which gets done automatically) and microG DroidGuard Helper is unchecked.

I don't know what's going on. Any explanation for that?

P.S. I'm going to uninstall microG DroidGuard Helper again, because it's pointless, unless someone can tell anything different.

**Comment by lss4** [comment] 2021-02-20 00:36
> ~Issue confirmed with microG Services Core Version `0.2.17.204714` and `0.2.16.204713` on ArrowOS 11 on a POCO X3 NFC, as well as the fix by downgrading to to `0.2.15.204713`.~
> 
> OK, that's awkward, I have just reinstalled microG Services Core Version `0.2.17.204714` and uninstalled microG DroidGuard Helper (because SafetyNet hasn't been working with microG for a long time anyway) and now the issue seems to be gone!
> 
> I'm using Magisk Canary (21410) and even reinstalling microG DroidGuard Helper after uninstalling it didn't stop it from working.
> 
> In MagiskHide microG Services Core is checked (which gets done automatically) and microG DroidGuard Helper is unchecked.
> 
> I don't know what's going on. Any explanation for that?
> 
> P.S. I'm going to uninstall microG DroidGuard Helper again, because it's pointless, unless someone can tell anything different.

I think there's a bug in the list display. If you expand DroidGuard Helper, it should become checked.

Actually NanoDroid has his own builds of DroidGuard Helper that attempted to fix Safety Net for a while (not sure if it's still working now)... but I personally don't really care about Safety Net anymore. Will try disabling DroidGuard Helper, but I don't think it'll make too much difference as I still cannot maintain a GCM connection for more than a minute.

**Comment by Master0ne** [comment] 2021-02-20 03:49
> I think there's a bug in the list display. If you expand DroidGuard Helper, it should become checked.

Didn't try and didn't care, already uninstalled DroidGuard Helper again.

> Actually NanoDroid has his own builds of DroidGuard Helper that attempted to fix Safety Net for a while (not sure if it's still working now)... but I personally don't really care about Safety Net anymore. Will try disabling DroidGuard Helper, but I don't think it'll make too much difference as I still cannot maintain a GCM connection for more than a minute.

AFAIK there is currently no way to pass SafetyNet when using microG, not even with the NanoDroid build. I remember that it was mentioned last year that it's supposedly being worked on but only has a low priority.

**Comment by guglovich** [comment] 2022-01-22 15:20
I have a similar problem. I can add an account, but it won't sync with Google. Phone too Redmi Note 8T (willow) on Arrow 12.0 Vanilla.

**Comment by ale5000-git** [comment] 2022-01-26 11:52
Everything should already be fixed on the latest version so I close it for now.
Open a new issue if needed.

**Closed by ale5000-git** 2022-01-26 11:52 UTC
Labels: bug
